import { createHash } from 'node:crypto';
import { lstat, readFile, readdir, realpath, unlink } from 'node:fs/promises';
import { isAbsolute, join, relative, sep } from 'node:path';
import { isDeepStrictEqual } from 'node:util';

import { atomicWriteValidated } from '../lib/atomic-write.mjs';
import { compareCodePoints } from '../lib/deterministic-order.mjs';
import { createError } from '../lib/errors.mjs';
import { parseRestrictedYaml } from '../lib/markdown.mjs';
import { fail, ok } from '../lib/result.mjs';
import { validateJson } from '../lib/validate-json.mjs';
import { validateAlignmentFeedbackPair } from './alignment-marker.mjs';
import { validateClosureSummary } from './close-delivery.mjs';

const GENERATED_NOTICE = '<!-- Generated by Project Lifecycle from validated active alignment state; do not edit. -->';
const MAX_INVENTORY_FILES = 2000;
const MAX_DOCUMENT_BYTES = 262_144;
const CLOSURE_SUMMARY_MARKER = /^<!-- project-lifecycle:closure-summary sha256=([0-9a-f]{64}) -->\n?/u;
const failure = (path, message) => fail([
  createError('ALIGNMENT_REVIEW_INPUT_INVALID', path, message),
]);
const safeTitle = (value) => typeof value === 'string'
  && value.trim() === value
  && value.length > 0
  && value.length <= 200
  && !/[\r\n\p{Cc}\p{Cf}]/u.test(value);
const sortedUnique = (values) => [...new Set(values)].sort(compareCodePoints);
const record = (value) => value !== null && typeof value === 'object' && !Array.isArray(value);
const canonicalize = (value) => {
  if (Array.isArray(value)) return value.map(canonicalize);
  if (!record(value)) return value;
  return Object.fromEntries(Object.keys(value).sort().map((key) => [key, canonicalize(value[key])]));
};
export const closureSummaryHash = (summary) => createHash('sha256')
  .update(JSON.stringify(canonicalize(summary)))
  .digest('hex');
const extractClosureSummaryHash = (body) => {
  const normalized = body.replaceAll('\r\n', '\n').replace(/^\n/u, '');
  const direct = CLOSURE_SUMMARY_MARKER.exec(normalized);
  if (direct) return direct[1];
  const title = /^(#[ \t]+[^\n]+\n(?:\n)?)/u.exec(normalized);
  return title ? CLOSURE_SUMMARY_MARKER.exec(normalized.slice(title[0].length))?.[1] ?? null : null;
};

const acceptedClosure = (closure, feedbackId) => closure?.outcome?.status === 'ACCEPTED'
  && closure?.acceptance?.claimed === true
  && Array.isArray(closure.feedback_coverage)
  && closure.feedback_coverage.some((entry) => entry?.feedback_id === feedbackId && entry.status === 'COVERED');

const rejectedClosure = (closure) => ['ABANDONED', 'CANCELLED', 'REJECTED'].includes(closure?.outcome?.status);
const coversFeedback = (closure, feedbackId) => Array.isArray(closure?.feedback_coverage)
  && closure.feedback_coverage.some((entry) => entry?.feedback_id === feedbackId);

export const deriveAlignmentReview = ({ feedbacks = [], owners = [], closures = [] } = {}) => {
  if (!Array.isArray(feedbacks) || !Array.isArray(owners) || !Array.isArray(closures)) {
    return failure('/', 'Alignment review inputs must be bounded arrays.');
  }
  const closureByOwner = new Map();
  for (const [index, closure] of closures.entries()) {
    if (!validateClosureSummary(closure).ok || closureByOwner.has(closure.owner_artifact_id)) {
      return failure(`/closures/${index}`, 'Closure summaries require unique owner references.');
    }
    closureByOwner.set(closure.owner_artifact_id, closure);
  }

  const ownerRecords = [];
  for (const [index, candidate] of owners.entries()) {
    const validation = validateJson('delivery-frontmatter', candidate);
    if (!validation.ok || !['prd', 'non-prd-delivery'].includes(candidate.artifact_kind)) {
      return failure(`/owners/${index}`, 'Alignment owners must be valid PRD or non-PRD delivery assets.');
    }
    ownerRecords.push(candidate);
  }

  const ids = new Set();
  const rows = [];
  for (const [index, record] of feedbacks.entries()) {
    const validation = validateJson('delivery-frontmatter', record?.frontmatter);
    if (!validation.ok || record.frontmatter.artifact_kind !== 'feedback'
      || record.frontmatter.retention_tier !== 'active') {
      return failure(`/feedbacks/${index}`, 'Alignment entries must reference valid Feedback Frontmatter.');
    }
    const feedbackId = record.frontmatter.artifact_id;
    if (ids.has(feedbackId)) return failure(`/feedbacks/${index}`, 'Feedback IDs must be unique.');
    ids.add(feedbackId);
    if (record.marker === null) continue;
    if (!validateJson('alignment-marker', record.marker).ok
      || record.marker.primary_domain_id !== record.frontmatter.domain_ids.find((id) => id === record.marker.primary_domain_id)
      || !safeTitle(record.titles?.en) || !safeTitle(record.titles?.['zh-CN'])) {
      return failure(`/feedbacks/${index}`, 'Active alignment Feedback must have one validated marker and localized titles.');
    }

    const linkedOwners = ownerRecords.filter((candidate) => candidate.relationships.feedback_ids.includes(feedbackId));
    const requiredOwners = [];
    const acceptedOwners = new Set();
    for (const candidate of linkedOwners) {
      const feedbackProject = record.frontmatter.current_project_id ?? record.frontmatter.project_id_at_creation;
      const ownerProject = candidate.current_project_id ?? candidate.project_id_at_creation;
      if (ownerProject !== feedbackProject) {
        return failure(`/owners/${candidate.artifact_id}`, 'Linked alignment owner must belong to the Feedback project.');
      }
      const closure = closureByOwner.get(candidate.artifact_id);
      if (closure && closure.baseline.starting !== candidate.knowledge_baseline) {
        return failure(`/closures/${candidate.artifact_id}`, 'Owner closure must match its starting knowledge baseline.');
      }
      if (rejectedClosure(closure)) {
        if (!coversFeedback(closure, feedbackId)) {
          return failure(`/closures/${candidate.artifact_id}`, 'Terminal closure must explicitly cover linked Feedback.');
        }
        continue;
      }
      requiredOwners.push(candidate.artifact_id);
      if (closure?.outcome?.status === 'ACCEPTED') {
        if (!acceptedClosure(closure, feedbackId)) {
          return failure(`/closures/${candidate.artifact_id}`, 'Accepted closure must explicitly cover linked Feedback.');
        }
        acceptedOwners.add(candidate.artifact_id);
      }
    }
    const ownerRef = sortedUnique(requiredOwners);
    const allAccepted = ownerRef.length > 0 && ownerRef.every((ownerId) => acceptedOwners.has(ownerId));
    const alignmentPhase = record.marker.routing_disposition === 'DEFERRED'
      ? 'DEFERRED'
      : ownerRef.length > 0 && !allAccepted
        ? 'DELIVERY_OPEN'
        : allAccepted
          ? 'KNOWLEDGE_WRITEBACK'
          : 'REVIEW_REQUIRED';
    rows.push({
      feedback_id: feedbackId,
      title: { en: record.titles.en, 'zh-CN': record.titles['zh-CN'] },
      primary_domain_id: record.marker.primary_domain_id,
      alignment_phase: alignmentPhase,
      owner_ref: ownerRef,
    });
  }
  rows.sort((left, right) => compareCodePoints(left.feedback_id, right.feedback_id));
  const review = { schema_version: 1, rows };
  const validation = validateJson('alignment-review', review);
  return validation.ok ? ok(review) : failure('/', 'Derived alignment review violates its closed schema.');
};

const escapeTable = (value) => value.replace(/[\\`*_\[\]{}()<>#+.!|~-]/gu, '\\$&');
const render = (review, language) => {
  const heading = language === 'en' ? 'Active alignment review' : '活动对齐审阅';
  const lines = [
    GENERATED_NOTICE,
    `# ${heading}`,
    '',
    '| feedback_id | title | primary_domain_id | alignment_phase | owner_ref |',
    '| --- | --- | --- | --- | --- |',
  ];
  for (const row of review.rows) {
    const owners = row.owner_ref.length === 0 ? '-' : row.owner_ref.map((value) => `\`${value}\``).join(', ');
    lines.push(`| \`${row.feedback_id}\` | ${escapeTable(row.title[language])} | \`${row.primary_domain_id}\` | \`${row.alignment_phase}\` | ${owners} |`);
  }
  return `${lines.join('\n')}\n`;
};

export const renderAlignmentReviewPair = (review) => ({
  en: render(review, 'en'),
  'zh-CN': render(review, 'zh-CN'),
});

const inside = (root, candidate) => {
  const path = relative(root, candidate);
  return path === '' || (path !== '..' && !path.startsWith(`..${sep}`) && !isAbsolute(path));
};

const regularDirectory = async (path, parent = null) => {
  const state = await lstat(path);
  const physical = await realpath(path);
  if (!state.isDirectory() || state.isSymbolicLink() || (parent && !inside(parent, physical))) {
    throw new Error('Unsafe alignment review directory.');
  }
  return physical;
};

const resolveLifecycleRoot = async (root) => {
  if (typeof root !== 'string' || !isAbsolute(root)) throw new Error('Absolute project root required.');
  const projectRoot = await regularDirectory(root);
  const docsRoot = await regularDirectory(join(root, 'docs'), projectRoot);
  const lifecycleRoot = await regularDirectory(join(root, 'docs', 'project-lifecycle'), docsRoot);
  await regularDirectory(join(root, 'docs', 'project-lifecycle', 'delivery'), lifecycleRoot);
  return lifecycleRoot;
};

const readExisting = async (path) => {
  try {
    const state = await lstat(path);
    if (!state.isFile() || state.isSymbolicLink()) throw new Error('Unsafe projection target.');
    return readFile(path, 'utf8');
  } catch (error) {
    if (error.code === 'ENOENT') return null;
    throw error;
  }
};

const splitDeliveryDocument = (source) => {
  const normalized = source.replaceAll('\r\n', '\n');
  if (!normalized.startsWith('---\n')) return null;
  const closing = normalized.indexOf('\n---\n', 4);
  if (closing === -1) return null;
  const parsed = parseRestrictedYaml(normalized.slice(4, closing), '/frontmatter');
  if (!parsed.ok || !validateJson('delivery-frontmatter', parsed.value).ok) return null;
  return { frontmatter: parsed.value, body: normalized.slice(closing + 5) };
};

const addPairLanguage = (pairs, document, name) => {
  const id = document.frontmatter.artifact_id;
  const language = name === `${id}-en.md`
    ? 'en'
    : name === `${id}.md`
      ? 'zh-CN'
      : null;
  if (language === null) throw new Error('Delivery inventory contains a non-canonical locator.');
  const pair = pairs.get(id) ?? {};
  if (pair[language]) throw new Error('Delivery inventory contains a duplicate language.');
  pair[language] = document;
  pairs.set(id, pair);
};

const discoverAlignmentInventory = async (lifecycleRoot) => {
  const roots = [await regularDirectory(join(lifecycleRoot, 'delivery'), lifecycleRoot)];
  try {
    roots.push(await regularDirectory(join(lifecycleRoot, 'archive', 'delivery'), lifecycleRoot));
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
  }
  const entries = [];
  for (const root of roots) {
    for (const name of await readdir(root)) {
      if (name.endsWith('.md')
        && !['alignment-review-en.md', 'alignment-review.md'].includes(name)) {
        entries.push({ root, name });
      }
    }
  }
  if (entries.length > MAX_INVENTORY_FILES) throw new Error('Delivery inventory is unbounded.');
  const pairs = new Map();
  for (const { root, name } of entries) {
    const path = join(root, name);
    const state = await lstat(path);
    if (!state.isFile() || state.isSymbolicLink() || state.size > MAX_DOCUMENT_BYTES) {
      throw new Error('Delivery inventory contains an unsafe document.');
    }
    const document = splitDeliveryDocument(await readFile(path, 'utf8'));
    if (!document) throw new Error('Delivery inventory contains an invalid document.');
    addPairLanguage(pairs, document, name);
  }

  const feedbacks = [];
  const owners = [];
  const closureProofs = new Set();
  for (const [id, pair] of pairs) {
    if (!pair.en || !pair['zh-CN']
      || !isDeepStrictEqual(pair.en.frontmatter, pair['zh-CN'].frontmatter)) {
      throw new Error(`Delivery pair ${id} is incomplete or divergent.`);
    }
    const frontmatter = pair.en.frontmatter;
    if (frontmatter.artifact_kind === 'feedback' && frontmatter.retention_tier === 'active') {
      const alignment = validateAlignmentFeedbackPair({
        frontmatter,
        bodies: { en: pair.en.body, 'zh-CN': pair['zh-CN'].body },
      });
      if (!alignment.ok) throw new Error('Active Feedback inventory is invalid.');
      if (alignment.value.marker !== null) {
        feedbacks.push({
          frontmatter,
          marker: alignment.value.marker,
          titles: alignment.value.titles,
        });
      }
    } else if (['prd', 'non-prd-delivery'].includes(frontmatter.artifact_kind)) {
      owners.push(frontmatter);
    } else if (frontmatter.artifact_kind === 'closure-summary') {
      const enHash = extractClosureSummaryHash(pair.en.body);
      const zhHash = extractClosureSummaryHash(pair['zh-CN'].body);
      if (enHash !== null && enHash === zhHash) closureProofs.add(`${frontmatter.artifact_id}:${enHash}`);
    }
  }
  const activeFeedbackIds = new Set(feedbacks.map(({ frontmatter }) => frontmatter.artifact_id));
  const linkedOwners = owners.filter(({ relationships }) => (
    relationships.feedback_ids.some((id) => activeFeedbackIds.has(id))
  ));
  const linkedOwnerIds = new Set(linkedOwners.map(({ artifact_id: id }) => id));
  return {
    feedbacks,
    owners: linkedOwners,
    closureProofs: new Set([...closureProofs].filter((proof) => {
      const id = proof.slice(0, proof.indexOf(':'));
      return id.startsWith('closure-') && linkedOwnerIds.has(id.slice('closure-'.length));
    })),
  };
};

const sameRecords = (supplied, authoritative, identity) => {
  const suppliedById = new Map(supplied.map((value) => [identity(value), value]));
  const authoritativeById = new Map(authoritative.map((value) => [identity(value), value]));
  return suppliedById.size === supplied.length
    && suppliedById.size === authoritativeById.size
    && [...authoritativeById].every(([id, value]) => isDeepStrictEqual(suppliedById.get(id), value));
};

const validateAuthoritativeInventory = async (lifecycleRoot, input) => {
  const inventory = await discoverAlignmentInventory(lifecycleRoot);
  const suppliedFeedbacks = input.feedbacks.filter(({ marker }) => marker !== null);
  const activeFeedbackIds = new Set(inventory.feedbacks.map(({ frontmatter }) => frontmatter.artifact_id));
  const suppliedOwners = input.owners.filter(({ relationships }) => (
    relationships.feedback_ids.some((id) => activeFeedbackIds.has(id))
  ));
  const linkedOwnerIds = new Set(inventory.owners.map(({ artifact_id: id }) => id));
  const suppliedClosures = input.closures.filter(({ owner_artifact_id: id }) => linkedOwnerIds.has(id));
  const suppliedClosureProofs = new Set(suppliedClosures.map((closure) => (
    `${closure.artifact_id}:${closureSummaryHash(closure)}`
  )));
  return sameRecords(suppliedFeedbacks, inventory.feedbacks, ({ frontmatter }) => frontmatter.artifact_id)
    && sameRecords(suppliedOwners, inventory.owners, ({ artifact_id: id }) => id)
    && suppliedClosureProofs.size === suppliedClosures.length
    && suppliedClosureProofs.size === inventory.closureProofs.size
    && [...suppliedClosureProofs].every((proof) => inventory.closureProofs.has(proof));
};

const writeContent = (write, lifecycleRoot, locator, content) => write({
  root: lifecycleRoot,
  target: locator,
  content,
  validate: async (source) => source === content
    ? ok(source)
    : failure('/', 'Generated projection content changed during publication.'),
});

const restore = async ({ write, remove, lifecycleRoot, locator, original }) => {
  if (original === null) {
    try {
      await remove(join(lifecycleRoot, locator));
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
    }
    return;
  }
  await writeContent(write, lifecycleRoot, locator, original);
};

export const syncAlignmentReview = async (input = {}, operations = {}) => {
  const review = deriveAlignmentReview(input);
  if (!review.ok) return review;
  let lifecycleRoot;
  try {
    lifecycleRoot = await resolveLifecycleRoot(input.root);
  } catch {
    return fail([createError('ALIGNMENT_REVIEW_PATH_INVALID', '/root', 'Projection targets require the fixed regular lifecycle root.')]);
  }
  const locators = {
    en: 'delivery/alignment-review-en.md',
    'zh-CN': 'delivery/alignment-review.md',
  };
  const paths = {
    en: join(lifecycleRoot, locators.en),
    'zh-CN': join(lifecycleRoot, locators['zh-CN']),
  };
  let existing;
  try {
    existing = {
      en: await readExisting(paths.en),
      'zh-CN': await readExisting(paths['zh-CN']),
    };
  } catch {
    return fail([createError('ALIGNMENT_REVIEW_PATH_INVALID', '/delivery', 'Projection targets must be regular files.')]);
  }
  if ((existing.en === null) !== (existing['zh-CN'] === null)) {
    return fail([createError('ALIGNMENT_REVIEW_PAIR_INCOMPLETE', '/delivery', 'Generated projection files must exist as a pair.')]);
  }
  if (existing.en !== null
    && (!existing.en.startsWith(`${GENERATED_NOTICE}\n`)
      || !existing['zh-CN'].startsWith(`${GENERATED_NOTICE}\n`))) {
    return fail([createError('ALIGNMENT_REVIEW_COLLISION', '/delivery', 'Projection locators are occupied by a non-generated delivery asset.')]);
  }
  try {
    if (!await validateAuthoritativeInventory(lifecycleRoot, input)) {
      return fail([createError(
        'ALIGNMENT_REVIEW_INVENTORY_INCOMPLETE',
        '/delivery',
        'Projection publication requires the complete authoritative Feedback, owner, and closure inventory.',
      )]);
    }
  } catch {
    return fail([createError(
      'ALIGNMENT_REVIEW_INVENTORY_INCOMPLETE',
      '/delivery',
      'Projection publication requires a complete valid bilingual delivery inventory.',
    )]);
  }
  const write = operations.atomicWriteValidated ?? atomicWriteValidated;
  const remove = operations.unlink ?? unlink;
  if (review.value.rows.length === 0) {
    if (existing.en === null) return ok({ row_count: 0, phases: [], locators, status: 'absent' });
    try {
      await remove(paths.en);
    } catch {
      return fail([createError('ALIGNMENT_REVIEW_WRITE_FAILED', '/delivery', 'Projection pair removal failed and was rolled back.')]);
    }
    try {
      await remove(paths['zh-CN']);
    } catch {
      try {
        await writeContent(write, lifecycleRoot, locators.en, existing.en);
      } catch {
        return fail([createError('ALIGNMENT_REVIEW_RECOVERY_REQUIRED', '/delivery', 'Projection removal and rollback both failed; manual recovery is required.')]);
      }
      return fail([createError('ALIGNMENT_REVIEW_WRITE_FAILED', '/delivery', 'Projection pair removal failed and was rolled back.')]);
    }
    return ok({ row_count: 0, phases: [], locators, status: 'removed' });
  }

  const pair = renderAlignmentReviewPair(review.value);
  try {
    await writeContent(write, lifecycleRoot, locators.en, pair.en);
  } catch {
    return fail([createError('ALIGNMENT_REVIEW_WRITE_FAILED', '/delivery', 'English projection publication failed before the pair completed.')]);
  }
  try {
    await writeContent(write, lifecycleRoot, locators['zh-CN'], pair['zh-CN']);
  } catch {
    try {
      await restore({ write, remove, lifecycleRoot, locator: locators.en, original: existing.en });
    } catch {
      return fail([createError('ALIGNMENT_REVIEW_RECOVERY_REQUIRED', '/delivery', 'Projection publication and rollback both failed; manual recovery is required.')]);
    }
    return fail([createError('ALIGNMENT_REVIEW_WRITE_FAILED', '/delivery', 'Projection pair publication failed and was rolled back.')]);
  }
  return ok({
    row_count: review.value.rows.length,
    phases: sortedUnique(review.value.rows.map(({ alignment_phase: phase }) => phase)),
    locators,
    status: existing.en === null ? 'created' : 'updated',
  });
};
