import { posix } from 'node:path';

import { compareCodePoints } from '../lib/deterministic-order.mjs';
import { createError } from '../lib/errors.mjs';
import { fail, ok } from '../lib/result.mjs';

const NOTICE = '<!-- Generated by Project Lifecycle from validated delivery Frontmatter; do not edit. -->';
const failure = (code, path, message) => fail([createError(code, path, message)]);
const languageName = (language) => language === 'en' ? 'INDEX-en.md' : 'INDEX.md';
const text = {
  en: { title: 'Delivery', feedback: 'Feedback', owners: 'Owners', retained: 'Retained owners', closures: 'Closure summaries', views: 'Views', assets: 'Owned assets', archive: 'Retained archive', empty: 'None.' },
  'zh-CN': { title: '交付', feedback: '反馈', owners: '所有者', retained: '保留的所有者', closures: '闭环摘要', views: '视图', assets: '所属文档', archive: '保留归档', empty: '无。' },
};

const entry = (item, language, fromDirectory) => {
  const locator = item.locators[language];
  const target = posix.relative(fromDirectory, locator);
  return `- [\`${item.artifact_id}\`](${target}) — kind: \`${item.artifact_kind}\`; retention: \`${item.retention_tier}\``;
};

const renderRoot = (inventory, language) => {
  const labels = text[language];
  const feedback = inventory.feedbacks.map((item) => entry(item, language, 'delivery'));
  const owners = inventory.owners.map((owner) => {
    const root = owner.artifact_kind === 'prd'
      ? `delivery/prds/${owner.artifact_id}`
      : `delivery/non-prd/${owner.artifact_id}`;
    return `- [\`${owner.artifact_id}\`](${posix.relative('delivery', `${root}/${languageName(language)}`)}) — kind: \`${owner.artifact_kind}\``;
  });
  const activeOwnerIds = new Set(inventory.owners.map(({ artifact_id: id }) => id));
  const retained = Object.values(inventory.archived_by_owner ?? {})
    .map(({ owner_artifact_id: ownerId, assets }) => assets.find(({ artifact_id: id, artifact_kind: kind }) => (
      id === ownerId && ['prd', 'non-prd-delivery'].includes(kind)
    )))
    .filter((owner) => owner && !activeOwnerIds.has(owner.artifact_id))
    .map((owner) => entry(owner, language, 'delivery'));
  const closures = (inventory.closed_summaries ?? []).map((item) => entry(item, language, 'delivery'));
  const views = (inventory.views ?? []).map((item) => {
    const target = posix.relative('delivery', item.locators[language]);
    return `- [\`${item.artifact_id}\`](${target})`;
  });
  return [
    NOTICE, `# ${labels.title}`,
    '', `## ${labels.feedback}`, '', ...(feedback.length ? feedback : [`- ${labels.empty}`]),
    '', `## ${labels.owners}`, '', ...(owners.length ? owners : [`- ${labels.empty}`]),
    '', `## ${labels.retained}`, '', ...(retained.length ? retained : [`- ${labels.empty}`]),
    '', `## ${labels.closures}`, '', ...(closures.length ? closures : [`- ${labels.empty}`]),
    '', `## ${labels.views}`, '', ...(views.length ? views : [`- ${labels.empty}`]),
    '',
  ].join('\n');
};

const renderOwner = (inventory, owner, language) => {
  const labels = text[language];
  const ownerRoot = owner.artifact_kind === 'prd'
    ? `delivery/prds/${owner.artifact_id}`
    : `delivery/non-prd/${owner.artifact_id}`;
  const active = inventory.by_owner[owner.artifact_id]?.assets
    ?? (inventory.closed_summaries ?? []).filter((item) => (
      item.owner_artifact_id === owner.artifact_id && item.locators.en.startsWith('delivery/')
    ));
  const archived = inventory.archived_by_owner[owner.artifact_id]?.assets ?? [];
  return [
    NOTICE,
    `# ${owner.artifact_id}`,
    '',
    `## ${labels.assets}`,
    '',
    ...(active.length ? active.map((item) => entry(item, language, ownerRoot)) : [`- ${labels.empty}`]),
    '',
    `## ${labels.archive}`,
    '',
    ...(archived.length ? archived.map((item) => entry(item, language, ownerRoot)) : [`- ${labels.empty}`]),
    '',
  ].join('\n');
};

export const generateDeliveryIndexes = async ({ inventory } = {}) => {
  if (!inventory || inventory.layout_version !== 2 || !Array.isArray(inventory.owners)) {
    return failure('DELIVERY_INDEX_INPUT_INVALID', '/inventory', 'A validated delivery inventory is required.');
  }
  const files = [];
  for (const language of ['en', 'zh-CN']) {
    files.push({ locator: `delivery/${languageName(language)}`, language, content: renderRoot(inventory, language) });
  }
  const ownersById = new Map(inventory.owners.map((owner) => [owner.artifact_id, owner]));
  for (const { owner_artifact_id: ownerId, assets } of Object.values(inventory.archived_by_owner ?? {})) {
    const retainedOwner = assets.find(({ artifact_id: id, artifact_kind: kind }) => (
      id === ownerId && ['prd', 'non-prd-delivery'].includes(kind)
    ));
    if (retainedOwner && !ownersById.has(ownerId)) ownersById.set(ownerId, retainedOwner);
  }
  const owners = [...ownersById.values()].sort((left, right) => compareCodePoints(left.artifact_id, right.artifact_id));
  for (const owner of owners) {
    const root = owner.artifact_kind === 'prd'
      ? `delivery/prds/${owner.artifact_id}`
      : `delivery/non-prd/${owner.artifact_id}`;
    for (const language of ['en', 'zh-CN']) {
      files.push({
        locator: `${root}/${languageName(language)}`,
        language,
        content: renderOwner(inventory, owner, language),
      });
    }
  }
  files.sort((left, right) => compareCodePoints(left.locator, right.locator));
  return ok({
    files,
    active_owner_ids: inventory.owners.map(({ artifact_id: id }) => id),
    retained_owner_ids: Object.keys(inventory.archived_by_owner).sort(compareCodePoints),
    feedback_ids: inventory.feedbacks.map(({ artifact_id: id }) => id),
  });
};
