import { posix } from 'node:path';

import { compareCodePoints } from '../lib/deterministic-order.mjs';
import { createError } from '../lib/errors.mjs';
import { fail, ok } from '../lib/result.mjs';

const NOTICE = '<!-- Generated by Project Lifecycle from validated delivery Frontmatter; do not edit. -->';
const failure = (code, path, message) => fail([createError(code, path, message)]);
const languageName = (language) => language === 'en' ? 'INDEX-en.md' : 'INDEX.md';
const text = {
  en: { title: 'Delivery', feedback: 'Feedback', owners: 'Owners', assets: 'Owned assets', archive: 'Retained archive', empty: 'None.' },
  'zh-CN': { title: '交付', feedback: '反馈', owners: '所有者', assets: '所属文档', archive: '保留归档', empty: '无。' },
};

const entry = (item, language, fromDirectory) => {
  const locator = item.locators[language];
  const target = posix.relative(fromDirectory, locator);
  return `- [\`${item.artifact_id}\`](${target}) — kind: \`${item.artifact_kind}\`; retention: \`${item.retention_tier}\``;
};

const renderRoot = (inventory, language) => {
  const labels = text[language];
  const feedback = inventory.feedbacks.map((item) => entry(item, language, 'delivery'));
  const owners = inventory.owners.map((owner) => {
    const root = owner.artifact_kind === 'prd'
      ? `delivery/prds/${owner.artifact_id}`
      : `delivery/non-prd/${owner.artifact_id}`;
    return `- [\`${owner.artifact_id}\`](${posix.relative('delivery', `${root}/${languageName(language)}`)}) — kind: \`${owner.artifact_kind}\``;
  });
  return [NOTICE, `# ${labels.title}`, '', `## ${labels.feedback}`, '', ...(feedback.length ? feedback : [`- ${labels.empty}`]), '', `## ${labels.owners}`, '', ...(owners.length ? owners : [`- ${labels.empty}`]), ''].join('\n');
};

const renderOwner = (inventory, owner, language) => {
  const labels = text[language];
  const ownerRoot = owner.artifact_kind === 'prd'
    ? `delivery/prds/${owner.artifact_id}`
    : `delivery/non-prd/${owner.artifact_id}`;
  const active = inventory.by_owner[owner.artifact_id]?.assets ?? [];
  const archived = inventory.archived_by_owner[owner.artifact_id]?.assets ?? [];
  return [
    NOTICE,
    `# ${owner.artifact_id}`,
    '',
    `## ${labels.assets}`,
    '',
    ...(active.length ? active.map((item) => entry(item, language, ownerRoot)) : [`- ${labels.empty}`]),
    '',
    `## ${labels.archive}`,
    '',
    ...(archived.length ? archived.map((item) => entry(item, language, ownerRoot)) : [`- ${labels.empty}`]),
    '',
  ].join('\n');
};

export const generateDeliveryIndexes = async ({ inventory } = {}) => {
  if (!inventory || inventory.layout_version !== 2 || !Array.isArray(inventory.owners)) {
    return failure('DELIVERY_INDEX_INPUT_INVALID', '/inventory', 'A validated delivery inventory is required.');
  }
  const files = [];
  for (const language of ['en', 'zh-CN']) {
    files.push({ locator: `delivery/${languageName(language)}`, language, content: renderRoot(inventory, language) });
  }
  for (const owner of inventory.owners) {
    const root = owner.artifact_kind === 'prd'
      ? `delivery/prds/${owner.artifact_id}`
      : `delivery/non-prd/${owner.artifact_id}`;
    for (const language of ['en', 'zh-CN']) {
      files.push({
        locator: `${root}/${languageName(language)}`,
        language,
        content: renderOwner(inventory, owner, language),
      });
    }
  }
  files.sort((left, right) => compareCodePoints(left.locator, right.locator));
  return ok({
    files,
    active_owner_ids: inventory.owners.map(({ artifact_id: id }) => id),
    retained_owner_ids: Object.keys(inventory.archived_by_owner).sort(compareCodePoints),
    feedback_ids: inventory.feedbacks.map(({ artifact_id: id }) => id),
  });
};
