import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';

import {
  inspectLegacyDeliveryLayout,
  migrateDeliveryLayout,
} from '../../scripts/delivery/delivery-layout-migration.mjs';
import { inspectLifecycleTree } from '../../scripts/knowledge/layout-transaction.mjs';

const frontmatter = (id, kind, overrides = {}) => ({
  schema_version: 1,
  artifact_id: id,
  artifact_kind: kind,
  primary_route: kind === 'feedback' ? 'KNOWLEDGE_UPDATE' : kind === 'non-prd-delivery' ? 'NON_PRD_DELIVERY' : 'PRD_DELIVERY',
  project_id_at_creation: 'sample-project',
  current_project_id: 'sample-project',
  domain_ids: ['wiki-workspace'],
  knowledge_baseline: 'baseline-1',
  relationships: { feedback_ids: [], prd_ids: [], legacy_artifact_refs: [] },
  retention_tier: 'active',
  reclassified_from_refs: [],
  obligations: [],
  ...overrides,
});

const writePair = async (root, metadata, { archived = false, external = false } = {}) => {
  const directory = join(root, 'docs/project-lifecycle', archived ? 'archive/delivery' : 'delivery');
  await mkdir(directory, { recursive: true });
  for (const language of ['en', 'zh-CN']) {
    const name = `${metadata.artifact_id}${language === 'en' ? '-en' : ''}.md`;
    const link = external && language === 'en'
      ? '\n[Project map](../project-map.json)\n[Architecture](architecture-shared-en.md "canonical")\n[External](https://example.test/spec)\n'
      : '';
    await writeFile(join(directory, name), `---\n${JSON.stringify(metadata)}\n---\n# ${metadata.artifact_id}${link}`);
  }
};

const createLegacy = async (context, { ambiguous = false, missingPair = false, mixed = false } = {}) => {
  const root = await mkdtemp(join(tmpdir(), 'delivery-layout-migration-'));
  context.after(() => rm(root, { recursive: true, force: true }));
  await mkdir(join(root, 'docs/project-lifecycle'), { recursive: true });
  await writeFile(join(root, 'docs/project-lifecycle/project-map.json'), '{}\n');
  await writePair(root, frontmatter('feedback-density', 'feedback'));
  await writePair(root, frontmatter('prd-wiki-v1', 'prd'), { external: true });
  await writePair(root, frontmatter('repair-wiki-v1', 'non-prd-delivery'));
  await writePair(root, frontmatter('architecture-shared', 'architecture', {
    relationships: { feedback_ids: [], prd_ids: ambiguous ? [] : ['prd-wiki-v1'], legacy_artifact_refs: [] },
  }));
  await writePair(root, frontmatter('closure-prd-wiki-v1', 'closure-summary', {
    current_project_id: undefined,
    relationships: { feedback_ids: [], prd_ids: ['prd-wiki-v1'], legacy_artifact_refs: [] },
    retention_tier: 'closed-summary',
  }));
  await writePair(root, frontmatter('architecture-archived', 'architecture', {
    current_project_id: undefined,
    relationships: { feedback_ids: [], prd_ids: ['prd-wiki-v1'], legacy_artifact_refs: [] },
    retention_tier: 'archive',
  }), { archived: true });
  const delivery = join(root, 'docs/project-lifecycle/delivery');
  await writeFile(join(delivery, 'alignment-review-en.md'), '<!-- Generated by Project Lifecycle from validated active alignment state; do not edit. -->\n');
  await writeFile(join(delivery, 'alignment-review.md'), '<!-- Generated by Project Lifecycle from validated active alignment state; do not edit. -->\n');
  if (missingPair) await rm(join(delivery, 'feedback-density.md'));
  if (mixed) await mkdir(join(delivery, 'prds'));
  return root;
};

test('previews a deterministic owner-centric migration without mutating the lifecycle tree', async (context) => {
  const root = await createLegacy(context);
  const before = await inspectLifecycleTree({ repositoryRoot: root });
  const preview = await inspectLegacyDeliveryLayout({
    root,
    owner_mappings: [{ artifact_id: 'architecture-shared', owner_artifact_id: 'prd-wiki-v1' }],
  });
  const after = await inspectLifecycleTree({ repositoryRoot: root });

  assert.equal(preview.ok, true, JSON.stringify(preview));
  assert.equal(preview.value.route, 'NON_PRD_DELIVERY', JSON.stringify(preview.value.needs_user));
  assert.equal(preview.value.selected_solution_id, 'solution-owner-centric-delivery-layout-v2');
  assert.match(preview.value.plan_hash, /^sha256:[0-9a-f]{64}$/u);
  assert.deepEqual(preview.value.moves.find(({ artifact_id: id }) => id === 'feedback-density').to, {
    en: 'delivery/feedback/feedback-density-en.md',
    'zh-CN': 'delivery/feedback/feedback-density.md',
  });
  assert.deepEqual(preview.value.moves.find(({ artifact_id: id }) => id === 'architecture-archived').to, {
    en: 'archive/delivery/prds/prd-wiki-v1/architecture/architecture-archived-en.md',
    'zh-CN': 'archive/delivery/prds/prd-wiki-v1/architecture/architecture-archived.md',
  });
  assert.deepEqual(preview.value.unresolved_external_links, [{
    source: 'delivery/prd-wiki-v1-en.md',
    scheme: 'https',
    authority: 'example.test',
    href_hash: 'sha256:3d7d97d14835d9e523c95881c5320869a7930f879312f3785525ea7861c3bbf9',
  }]);
  assert.deepEqual(preview.value.managed_reference_rewrites, [
    {
      source: 'delivery/prd-wiki-v1-en.md',
      href: '../project-map.json',
      rewritten_href: '../../../project-map.json',
    },
    {
      source: 'delivery/prd-wiki-v1-en.md',
      href: 'architecture-shared-en.md',
      rewritten_href: 'architecture/architecture-shared-en.md',
    },
  ]);
  assert.equal(Object.isFrozen(preview.value), true);
  assert.deepEqual(after, before);
});

test('does not echo credential-bearing external URLs or crash on unmapped child links', async (context) => {
  const root = await createLegacy(context, { ambiguous: true });
  const delivery = join(root, 'docs/project-lifecycle/delivery');
  const child = frontmatter('architecture-shared', 'architecture');
  const protectedUrl = ['https://user', 'value@example.test/spec?session=value'].join(':');
  for (const language of ['en', 'zh-CN']) {
    const name = `architecture-shared${language === 'en' ? '-en' : ''}.md`;
    await writeFile(join(delivery, name), `---\n${JSON.stringify(child)}\n---\n# child\n[Owner](prd-wiki-v1-en.md)\n[Protected](${protectedUrl})\n`);
  }

  const preview = await inspectLegacyDeliveryLayout({ root });

  assert.equal(preview.ok, true, JSON.stringify(preview));
  assert.equal(preview.value.route, 'NEEDS_USER');
  assert.equal(JSON.stringify(preview.value).includes('user:value'), false);
  assert.equal(JSON.stringify(preview.value).includes('session=value'), false);
});

test('returns NEEDS_USER for ambiguous ownership, incomplete pairs, mixed layout, and contradictory mappings', async (context) => {
  for (const options of [{ ambiguous: true }, { missingPair: true }, { mixed: true }]) {
    const root = await createLegacy(context, options);
    const preview = await inspectLegacyDeliveryLayout({ root });
    assert.equal(preview.ok, true);
    assert.equal(preview.value.route, 'NEEDS_USER');
    assert.ok(preview.value.needs_user.length > 0);
  }
  const root = await createLegacy(context);
  const contradictory = await inspectLegacyDeliveryLayout({
    root,
    owner_mappings: [{ artifact_id: 'architecture-shared', owner_artifact_id: 'repair-wiki-v1' }],
  });
  assert.equal(contradictory.value.route, 'NEEDS_USER');
  assert.ok(contradictory.value.needs_user.some(({ code }) => code === 'OWNER_MAPPING_CONTRADICTORY'));
});

test('requires exact approval and backup references before migration', async (context) => {
  const root = await createLegacy(context);
  const owner_mappings = [{ artifact_id: 'architecture-shared', owner_artifact_id: 'prd-wiki-v1' }];
  const preview = await inspectLegacyDeliveryLayout({ root, owner_mappings });
  const result = await migrateDeliveryLayout({
    root,
    owner_mappings,
    plan_hash: preview.value.plan_hash,
    source_fingerprint: preview.value.source_fingerprint,
  });
  assert.equal(result.ok, false);
  assert.equal(result.errors[0].code, 'DELIVERY_MIGRATION_APPROVAL_REQUIRED');
});

test('restores the legacy tree when publication fails late', async (context) => {
  const root = await createLegacy(context);
  const owner_mappings = [{ artifact_id: 'architecture-shared', owner_artifact_id: 'prd-wiki-v1' }];
  const preview = await inspectLegacyDeliveryLayout({ root, owner_mappings });
  const before = await inspectLifecycleTree({ repositoryRoot: root });
  const result = await migrateDeliveryLayout({
    root,
    owner_mappings,
    plan_hash: preview.value.plan_hash,
    source_fingerprint: preview.value.source_fingerprint,
    approval_ref: 'approval:delivery-layout-v2',
    backup_ref: 'backup:delivery-layout-v1',
  }, {
    afterPublish: async () => { throw new Error('injected late failure'); },
  });
  const after = await inspectLifecycleTree({ repositoryRoot: root });
  assert.equal(result.ok, false);
  assert.deepEqual(after, before);
  await assert.rejects(readFile(join(root, 'docs/project-lifecycle/delivery/layout.json')), { code: 'ENOENT' });
});

test('rolls back a retained publication when live v2 validation fails', async (context) => {
  const root = await createLegacy(context);
  const owner_mappings = [{ artifact_id: 'architecture-shared', owner_artifact_id: 'prd-wiki-v1' }];
  const preview = await inspectLegacyDeliveryLayout({ root, owner_mappings });
  const before = await inspectLifecycleTree({ repositoryRoot: root });
  const result = await migrateDeliveryLayout({
    root,
    owner_mappings,
    plan_hash: preview.value.plan_hash,
    source_fingerprint: preview.value.source_fingerprint,
    approval_ref: 'approval:delivery-layout-v2',
    backup_ref: 'backup:delivery-layout-v1',
  }, {
    validatePublished: async () => ({
      ok: false,
      value: null,
      errors: [{ code: 'INJECTED_VALIDATION_FAILURE', path: '/', message: 'Injected.' }],
    }),
  });
  assert.equal(result.ok, false);
  assert.equal(result.errors[0].code, 'INJECTED_VALIDATION_FAILURE');
  assert.deepEqual(await inspectLifecycleTree({ repositoryRoot: root }), before);
});

test('atomically publishes v2 documents and generated indexes', async (context) => {
  const root = await createLegacy(context);
  const owner_mappings = [{ artifact_id: 'architecture-shared', owner_artifact_id: 'prd-wiki-v1' }];
  const preview = await inspectLegacyDeliveryLayout({ root, owner_mappings });
  const result = await migrateDeliveryLayout({
    root,
    owner_mappings,
    plan_hash: preview.value.plan_hash,
    source_fingerprint: preview.value.source_fingerprint,
    approval_ref: 'approval:delivery-layout-v2',
    backup_ref: 'backup:delivery-layout-v1',
  });
  assert.equal(result.ok, true, JSON.stringify(result));
  assert.equal(result.value.layout_version, 2);
  assert.equal(result.value.backup_ref, 'backup:delivery-layout-v1');
  assert.deepEqual(result.value.moved_locators, preview.value.moves);
  assert.match(result.value.validation_ref, /^sha256:[0-9a-f]{64}$/u);
  assert.deepEqual(JSON.parse(await readFile(join(root, 'docs/project-lifecycle/delivery/layout.json'), 'utf8')), {
    schema_version: 1,
    layout_version: 2,
  });
  const architecture = await readFile(join(root, 'docs/project-lifecycle/delivery/prds/prd-wiki-v1/architecture/architecture-shared-en.md'), 'utf8');
  assert.match(architecture, /schema_version: 2/u);
  assert.match(architecture, /owner_artifact_id: prd-wiki-v1/u);
  assert.match(architecture, /# architecture-shared/u);
  const owner = await readFile(join(root, 'docs/project-lifecycle/delivery/prds/prd-wiki-v1/prd-wiki-v1-en.md'), 'utf8');
  assert.match(owner, /\[Project map\]\(\.\.\/\.\.\/\.\.\/project-map\.json\)/u);
  assert.match(owner, /\[Architecture\]\(architecture\/architecture-shared-en\.md "canonical"\)/u);
  assert.match(await readFile(join(root, 'docs/project-lifecycle/delivery/INDEX-en.md'), 'utf8'), /prd-wiki-v1/u);
  assert.match(await readFile(join(root, 'docs/project-lifecycle/delivery/prds/prd-wiki-v1/INDEX-en.md'), 'utf8'), /architecture-shared/u);
  await assert.rejects(readFile(join(root, 'docs/project-lifecycle/delivery/prd-wiki-v1-en.md')), { code: 'ENOENT' });
});
