import assert from 'node:assert/strict';
import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';

import { inspectLegacyDeliveryLayout } from '../../scripts/delivery/delivery-layout-migration.mjs';
import { inspectLifecycleTree } from '../../scripts/knowledge/layout-transaction.mjs';

const frontmatter = (id, kind, overrides = {}) => ({
  schema_version: 1,
  artifact_id: id,
  artifact_kind: kind,
  primary_route: kind === 'feedback' ? 'KNOWLEDGE_UPDATE' : kind === 'non-prd-delivery' ? 'NON_PRD_DELIVERY' : 'PRD_DELIVERY',
  project_id_at_creation: 'sample-project',
  current_project_id: 'sample-project',
  domain_ids: ['wiki-workspace'],
  knowledge_baseline: 'baseline-1',
  relationships: { feedback_ids: [], prd_ids: [], legacy_artifact_refs: [] },
  retention_tier: 'active',
  reclassified_from_refs: [],
  obligations: [],
  ...overrides,
});

const writePair = async (root, metadata, { archived = false, external = false } = {}) => {
  const directory = join(root, 'docs/project-lifecycle', archived ? 'archive/delivery' : 'delivery');
  await mkdir(directory, { recursive: true });
  for (const language of ['en', 'zh-CN']) {
    const name = `${metadata.artifact_id}${language === 'en' ? '-en' : ''}.md`;
    const link = external && language === 'en'
      ? '\n[Architecture](architecture-shared-en.md)\n[External](https://example.test/spec)\n'
      : '';
    await writeFile(join(directory, name), `---\n${JSON.stringify(metadata)}\n---\n# ${metadata.artifact_id}${link}`);
  }
};

const createLegacy = async (context, { ambiguous = false, missingPair = false, mixed = false } = {}) => {
  const root = await mkdtemp(join(tmpdir(), 'delivery-layout-migration-'));
  context.after(() => rm(root, { recursive: true, force: true }));
  await writePair(root, frontmatter('feedback-density', 'feedback'));
  await writePair(root, frontmatter('prd-wiki-v1', 'prd'), { external: true });
  await writePair(root, frontmatter('repair-wiki-v1', 'non-prd-delivery'));
  await writePair(root, frontmatter('architecture-shared', 'architecture', {
    relationships: { feedback_ids: [], prd_ids: ambiguous ? [] : ['prd-wiki-v1'], legacy_artifact_refs: [] },
  }));
  await writePair(root, frontmatter('closure-prd-wiki-v1', 'closure-summary', {
    current_project_id: undefined,
    relationships: { feedback_ids: [], prd_ids: ['prd-wiki-v1'], legacy_artifact_refs: [] },
    retention_tier: 'closed-summary',
  }));
  await writePair(root, frontmatter('architecture-archived', 'architecture', {
    current_project_id: undefined,
    relationships: { feedback_ids: [], prd_ids: ['prd-wiki-v1'], legacy_artifact_refs: [] },
    retention_tier: 'archive',
  }), { archived: true });
  const delivery = join(root, 'docs/project-lifecycle/delivery');
  await writeFile(join(delivery, 'alignment-review-en.md'), '<!-- Generated by Project Lifecycle from validated active alignment state; do not edit. -->\n');
  await writeFile(join(delivery, 'alignment-review.md'), '<!-- Generated by Project Lifecycle from validated active alignment state; do not edit. -->\n');
  if (missingPair) await rm(join(delivery, 'feedback-density.md'));
  if (mixed) await mkdir(join(delivery, 'prds'));
  return root;
};

test('previews a deterministic owner-centric migration without mutating the lifecycle tree', async (context) => {
  const root = await createLegacy(context);
  const before = await inspectLifecycleTree({ repositoryRoot: root });
  const preview = await inspectLegacyDeliveryLayout({
    root,
    owner_mappings: [{ artifact_id: 'architecture-shared', owner_artifact_id: 'prd-wiki-v1' }],
  });
  const after = await inspectLifecycleTree({ repositoryRoot: root });

  assert.equal(preview.ok, true, JSON.stringify(preview));
  assert.equal(preview.value.route, 'NON_PRD_DELIVERY', JSON.stringify(preview.value.needs_user));
  assert.equal(preview.value.selected_solution_id, 'solution-owner-centric-delivery-layout-v2');
  assert.match(preview.value.plan_hash, /^sha256:[0-9a-f]{64}$/u);
  assert.deepEqual(preview.value.moves.find(({ artifact_id: id }) => id === 'feedback-density').to, {
    en: 'delivery/feedback/feedback-density-en.md',
    'zh-CN': 'delivery/feedback/feedback-density.md',
  });
  assert.deepEqual(preview.value.moves.find(({ artifact_id: id }) => id === 'architecture-archived').to, {
    en: 'archive/delivery/prds/prd-wiki-v1/architecture/architecture-archived-en.md',
    'zh-CN': 'archive/delivery/prds/prd-wiki-v1/architecture/architecture-archived.md',
  });
  assert.deepEqual(preview.value.unresolved_external_links, [{
    source: 'delivery/prd-wiki-v1-en.md',
    href: 'https://example.test/spec',
  }]);
  assert.deepEqual(preview.value.managed_reference_rewrites, [{
    source: 'delivery/prd-wiki-v1-en.md',
    href: 'architecture-shared-en.md',
    rewritten_href: 'architecture/architecture-shared-en.md',
  }]);
  assert.equal(Object.isFrozen(preview.value), true);
  assert.deepEqual(after, before);
});

test('returns NEEDS_USER for ambiguous ownership, incomplete pairs, mixed layout, and contradictory mappings', async (context) => {
  for (const options of [{ ambiguous: true }, { missingPair: true }, { mixed: true }]) {
    const root = await createLegacy(context, options);
    const preview = await inspectLegacyDeliveryLayout({ root });
    assert.equal(preview.ok, true);
    assert.equal(preview.value.route, 'NEEDS_USER');
    assert.ok(preview.value.needs_user.length > 0);
  }
  const root = await createLegacy(context);
  const contradictory = await inspectLegacyDeliveryLayout({
    root,
    owner_mappings: [{ artifact_id: 'architecture-shared', owner_artifact_id: 'repair-wiki-v1' }],
  });
  assert.equal(contradictory.value.route, 'NEEDS_USER');
  assert.ok(contradictory.value.needs_user.some(({ code }) => code === 'OWNER_MAPPING_CONTRADICTORY'));
});
