import assert from 'node:assert/strict';
import { mkdir, mkdtemp, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import test from 'node:test';

import { stringify as stringifyYaml } from 'yaml';

import { collectDeliveryInventory } from '../../scripts/delivery/delivery-inventory.mjs';
import { generateDeliveryIndexes } from '../../scripts/delivery/delivery-indexes.mjs';
import { deliveryLayoutContent } from '../../scripts/delivery/delivery-layout.mjs';

const frontmatter = ({
  artifact_id,
  artifact_kind,
  owner_artifact_id,
  retention_tier = 'active',
  current_project_id = retention_tier === 'active' ? 'sample-project' : undefined,
}) => ({
  schema_version: 2,
  artifact_id,
  ...(owner_artifact_id ? { owner_artifact_id } : {}),
  artifact_kind,
  primary_route: artifact_kind === 'non-prd-delivery' ? 'NON_PRD_DELIVERY' : 'PRD_DELIVERY',
  project_id_at_creation: 'sample-project',
  ...(current_project_id ? { current_project_id } : {}),
  domain_ids: ['wiki-workspace'],
  knowledge_baseline: 'baseline-7',
  relationships: { feedback_ids: [], prd_ids: [], legacy_artifact_refs: [] },
  retention_tier,
  reclassified_from_refs: [],
  obligations: [],
});

const document = (metadata, title = metadata.artifact_id) => (
  `---\n${stringifyYaml(metadata, { lineWidth: 0 }).trimEnd()}\n---\n# ${title}\n`
);

const writePair = async (lifecycleRoot, en, metadata) => {
  const zh = en.replace(/-en\.md$/u, '.md');
  await mkdir(dirname(join(lifecycleRoot, en)), { recursive: true });
  await Promise.all([
    writeFile(join(lifecycleRoot, en), document(metadata)),
    writeFile(join(lifecycleRoot, zh), document(metadata)),
  ]);
};

const fixture = async (context) => {
  const root = await mkdtemp(join(tmpdir(), 'project-lifecycle-delivery-indexes-'));
  context.after(() => rm(root, { recursive: true, force: true }));
  const lifecycleRoot = join(root, 'docs/project-lifecycle');
  await mkdir(join(lifecycleRoot, 'delivery/views'), { recursive: true });
  await writeFile(join(lifecycleRoot, 'delivery/layout.json'), deliveryLayoutContent());

  await writePair(lifecycleRoot, 'delivery/feedback/feedback-density-en.md', frontmatter({
    artifact_id: 'feedback-density', artifact_kind: 'feedback',
  }));
  await writePair(lifecycleRoot, 'delivery/prds/prd-search-v1/prd-search-v1-en.md', frontmatter({
    artifact_id: 'prd-search-v1', artifact_kind: 'prd', owner_artifact_id: 'prd-search-v1',
  }));
  await writePair(lifecycleRoot, 'delivery/prds/prd-search-v1/closure/closure-prd-search-v1-en.md', frontmatter({
    artifact_id: 'closure-prd-search-v1', artifact_kind: 'closure-summary', owner_artifact_id: 'prd-search-v1',
    retention_tier: 'closed-summary',
  }));
  await writePair(lifecycleRoot, 'delivery/prds/prd-wiki-v1/prd-wiki-v1-en.md', frontmatter({
    artifact_id: 'prd-wiki-v1', artifact_kind: 'prd', owner_artifact_id: 'prd-wiki-v1',
  }));
  for (const [directory, artifact_kind, artifact_id] of [
    ['architecture', 'architecture', 'architecture-wiki-v1'],
    ['batches', 'batch', 'batch-wiki-v1'],
    ['test-reports', 'test-report', 'test-wiki-v1'],
  ]) {
    await writePair(lifecycleRoot, `delivery/prds/prd-wiki-v1/${directory}/${artifact_id}-en.md`, frontmatter({
      artifact_id, artifact_kind, owner_artifact_id: 'prd-wiki-v1',
    }));
  }
  await writePair(lifecycleRoot, 'delivery/non-prd/non-prd-index-repair/non-prd-index-repair-en.md', frontmatter({
    artifact_id: 'non-prd-index-repair', artifact_kind: 'non-prd-delivery', owner_artifact_id: 'non-prd-index-repair',
  }));
  await writePair(lifecycleRoot, 'archive/delivery/prds/prd-wiki-v1/architecture/architecture-wiki-v1-retained-en.md', frontmatter({
    artifact_id: 'architecture-wiki-v1-retained', artifact_kind: 'architecture', owner_artifact_id: 'prd-wiki-v1',
    retention_tier: 'archive',
  }));
  await writePair(lifecycleRoot, 'archive/delivery/prds/prd-retained-v1/prd-retained-v1-en.md', frontmatter({
    artifact_id: 'prd-retained-v1', artifact_kind: 'prd', owner_artifact_id: 'prd-retained-v1',
    retention_tier: 'archive',
  }));
  const notice = '<!-- Generated by Project Lifecycle from validated active alignment state; do not edit. -->\n';
  await writeFile(join(lifecycleRoot, 'delivery/views/alignment-review-en.md'), `${notice}# Review\n`);
  await writeFile(join(lifecycleRoot, 'delivery/views/alignment-review.md'), `${notice}# 审阅\n`);
  return { root, lifecycleRoot };
};

test('collects canonical v2 pairs by one physical owner and renders paired indexes', async (context) => {
  const { lifecycleRoot } = await fixture(context);

  const result = await collectDeliveryInventory({ lifecycleRoot });

  assert.equal(result.ok, true, JSON.stringify(result));
  assert.deepEqual(result.value.owners.map(({ artifact_id }) => artifact_id), [
    'non-prd-index-repair',
    'prd-search-v1',
    'prd-wiki-v1',
  ]);
  assert.deepEqual(result.value.by_owner['prd-wiki-v1'].assets.map(({ artifact_id }) => artifact_id), [
    'architecture-wiki-v1',
    'batch-wiki-v1',
    'prd-wiki-v1',
    'test-wiki-v1',
  ]);
  assert.deepEqual(result.value.archived_by_owner['prd-wiki-v1'].assets.map(({ artifact_id }) => artifact_id), [
    'architecture-wiki-v1-retained',
  ]);
  assert.deepEqual(result.value.feedbacks.map(({ artifact_id }) => artifact_id), ['feedback-density']);
  assert.deepEqual(result.value.closed_summaries.map(({ artifact_id }) => artifact_id), ['closure-prd-search-v1']);
  assert.deepEqual(result.value.views.map(({ artifact_id }) => artifact_id), ['alignment-review']);

  const indexes = await generateDeliveryIndexes({ lifecycleRoot, inventory: result.value });
  assert.equal(indexes.ok, true, JSON.stringify(indexes));
  assert.deepEqual(indexes.value.files.map(({ locator }) => locator), [
    'delivery/INDEX-en.md',
    'delivery/INDEX.md',
    'delivery/non-prd/non-prd-index-repair/INDEX-en.md',
    'delivery/non-prd/non-prd-index-repair/INDEX.md',
    'delivery/prds/prd-search-v1/INDEX-en.md',
    'delivery/prds/prd-search-v1/INDEX.md',
    'delivery/prds/prd-wiki-v1/INDEX-en.md',
    'delivery/prds/prd-wiki-v1/INDEX.md',
  ]);
  assert.match(indexes.value.files[0].content, /prd-wiki-v1/u);
  assert.match(indexes.value.files[0].content, /prd-retained-v1/u);
  assert.match(indexes.value.files[0].content, /closure-prd-search-v1/u);
  assert.match(indexes.value.files[0].content, /alignment-review/u);
  assert.doesNotMatch(indexes.value.files[0].content, /# Architecture wiki/u);
});

test('rejects half pairs, path mismatches, unknown files, symlinks, and noncanonical overlays', async (context) => {
  const half = await fixture(context);
  await rm(join(half.lifecycleRoot, 'delivery/feedback/feedback-density.md'));
  assert.equal((await collectDeliveryInventory({ lifecycleRoot: half.lifecycleRoot })).ok, false);

  const mismatch = await fixture(context);
  await writePair(mismatch.lifecycleRoot, 'delivery/prds/prd-wiki-v1/architecture/wrong-en.md', frontmatter({
    artifact_id: 'architecture-wiki-v1-wrong', artifact_kind: 'architecture', owner_artifact_id: 'prd-wiki-v1',
  }));
  assert.equal((await collectDeliveryInventory({ lifecycleRoot: mismatch.lifecycleRoot })).ok, false);

  const unknown = await fixture(context);
  await writeFile(join(unknown.lifecycleRoot, 'delivery/notes.txt'), 'unknown\n');
  assert.equal((await collectDeliveryInventory({ lifecycleRoot: unknown.lifecycleRoot })).ok, false);

  const linked = await fixture(context);
  const outside = await mkdtemp(join(tmpdir(), 'project-lifecycle-delivery-indexes-outside-'));
  context.after(() => rm(outside, { recursive: true, force: true }));
  await symlink(outside, join(linked.lifecycleRoot, 'delivery/prds/link'));
  assert.equal((await collectDeliveryInventory({ lifecycleRoot: linked.lifecycleRoot })).ok, false);

  const overlay = await fixture(context);
  assert.equal((await collectDeliveryInventory({
    lifecycleRoot: overlay.lifecycleRoot,
    overlays: { 'delivery/prds/prd-wiki-v1/manual/custom-en.md': '# invalid\n' },
  })).ok, false);

  const orphan = await fixture(context);
  await Promise.all([
    rm(join(orphan.lifecycleRoot, 'delivery/prds/prd-wiki-v1/prd-wiki-v1-en.md')),
    rm(join(orphan.lifecycleRoot, 'delivery/prds/prd-wiki-v1/prd-wiki-v1.md')),
  ]);
  const orphanResult = await collectDeliveryInventory({ lifecycleRoot: orphan.lifecycleRoot });
  assert.equal(orphanResult.ok, false);
  assert.equal(orphanResult.errors[0].code, 'DELIVERY_INVENTORY_OWNER_MISSING');
});

test('rejects delivery trees beyond the managed depth and file-count bounds', async (context) => {
  const deep = await fixture(context);
  await mkdir(join(deep.lifecycleRoot, 'delivery/prds/prd-wiki-v1/architecture/too/deep'), { recursive: true });
  assert.equal((await collectDeliveryInventory({ lifecycleRoot: deep.lifecycleRoot })).ok, false);

  const crowded = await fixture(context);
  const extras = join(crowded.lifecycleRoot, 'delivery/feedback');
  await Promise.all(Array.from({ length: 2001 }, (_, index) => (
    writeFile(join(extras, `overflow-${String(index).padStart(4, '0')}.tmp`), '')
  )));
  assert.equal((await collectDeliveryInventory({ lifecycleRoot: crowded.lifecycleRoot })).ok, false);
});
