import { lstat, open, readdir, realpath } from 'node:fs/promises';
import { basename, isAbsolute, join, posix, relative, resolve, sep } from 'node:path';
import { isDeepStrictEqual } from 'node:util';

import { compareCodePoints } from '../lib/deterministic-order.mjs';
import { createError } from '../lib/errors.mjs';
import { parseRestrictedYaml } from '../lib/markdown.mjs';
import { fail, ok } from '../lib/result.mjs';
import { isSafeLocator, isSafeReference } from '../lib/reference-safety.mjs';
import { validateJson } from '../lib/validate-json.mjs';
import { pairForDomain, planKnowledgeLayout } from './layout-planner.mjs';

const NOTICE = '<!-- Generated by Project Lifecycle from project-map and validated Frontmatter; do not edit. -->';
const LANGUAGES = ['en', 'zh-CN'];
const same = isDeepStrictEqual;
const failure = (code, path, message) => fail([createError(code, path, message)]);
const record = (value) => value !== null && typeof value === 'object' && !Array.isArray(value);

// References rendered inside code spans and generated HTML comments must be
// portable single-line tokens. Colons, slashes, hashes, and at-signs remain
// valid; control/spacing, Markdown delimiters, and HTML comment breaks do not.
const safeLocator = (value) => typeof value === 'string'
  && isSafeLocator(value);

const inside = (root, candidate) => {
  const fromRoot = relative(root, candidate);
  return fromRoot === '' || (fromRoot !== '..' && !fromRoot.startsWith(`..${sep}`) && !isAbsolute(fromRoot));
};

const readFrontmatterPrefix = async (path, maxBytes = 65_536) => {
  const handle = await open(path, 'r');
  try {
    const prefix = Buffer.alloc(maxBytes);
    const delimiters = [Buffer.from('\n---\n'), Buffer.from('\r\n---\r\n')];
    for (let position = 0; position < maxBytes; position += 1) {
      const { bytesRead } = await handle.read(prefix, position, 1, position);
      if (bytesRead === 0) break;
      const length = position + 1;
      if (delimiters.some((delimiter) => (
        length >= delimiter.length
        && prefix.subarray(length - delimiter.length, length).equals(delimiter)
      ))) {
        return prefix.subarray(0, length).toString('utf8');
      }
    }
    throw new Error('Frontmatter boundary is missing or too large.');
  } finally {
    await handle.close();
  }
};

const frontmatterFromSource = (source, schema) => {
  if (typeof source !== 'string') return null;
  const normalized = source.replaceAll('\r\n', '\n');
  const closing = normalized.indexOf('\n---\n', 4);
  if (!normalized.startsWith('---\n') || closing === -1) return null;
  const parsed = parseRestrictedYaml(normalized.slice(4, closing), '/frontmatter');
  if (!parsed.ok || !validateJson(schema, parsed.value).ok) return null;
  return parsed.value;
};

const readBoundedFrontmatter = async (lifecycleRoot, locator, schema, overlays) => {
  if (!safeLocator(locator)) throw Object.assign(new Error('Unsafe navigation locator.'), { code: 'INDEX_TARGET_INVALID' });
  const overlay = overlays.get(locator);
  if (overlay !== undefined) {
    const frontmatter = frontmatterFromSource(overlay, schema);
    if (!frontmatter) throw Object.assign(new Error('Invalid navigation overlay.'), { code: 'INDEX_FRONTMATTER_INVALID' });
    return frontmatter;
  }
  const lexical = resolve(lifecycleRoot, locator);
  const state = await lstat(lexical);
  const physical = await realpath(lexical);
  if (!state.isFile() || state.isSymbolicLink() || !inside(lifecycleRoot, physical)) {
    throw Object.assign(new Error('Navigation locator escapes the lifecycle root.'), { code: 'PATH_SYMLINK_ESCAPE' });
  }
  const frontmatter = frontmatterFromSource(await readFrontmatterPrefix(physical), schema);
  if (!frontmatter) throw Object.assign(new Error('Invalid navigation Frontmatter.'), { code: 'INDEX_FRONTMATTER_INVALID' });
  return frontmatter;
};

const validateDescriptor = (entry, schema, path) => {
  if (!record(entry) || !LANGUAGES.includes(entry.language) || !safeLocator(entry.locator)) {
    return failure('INDEX_TARGET_INVALID', path, 'Navigation inputs require one bounded localized locator.');
  }
  const validation = validateJson(schema, entry.frontmatter);
  return validation.ok ? ok(entry) : failure(
    'INDEX_FRONTMATTER_INVALID',
    `${path}/frontmatter`,
    'Navigation Frontmatter does not satisfy its shared contract.',
  );
};

const pairEntries = (entries, { idOf, schema, path }) => {
  const byId = new Map();
  for (const [index, entry] of entries.entries()) {
    const validation = validateDescriptor(entry, schema, `${path}/${index}`);
    if (!validation.ok) return validation;
    const id = idOf(entry.frontmatter);
    const pair = byId.get(id) ?? {};
    if (pair[entry.language]) {
      return failure('INDEX_OWNERSHIP_DUPLICATE', `${path}/${index}`, 'One logical asset may have only one owner per language.');
    }
    pair[entry.language] = entry;
    byId.set(id, pair);
  }
  for (const [id, pair] of byId) {
    if (!pair.en || !pair['zh-CN']) {
      return failure('INDEX_PAIR_INVALID', `${path}/${id}`, 'Both localized Frontmatter views are required.');
    }
    if (!same(pair.en.frontmatter, pair['zh-CN'].frontmatter)) {
      return failure('INDEX_PAIR_INVALID', `${path}/${id}`, 'Localized views must share identical machine Frontmatter.');
    }
  }
  return ok(byId);
};

const relationshipToken = (domain) => [...domain.relationships]
  .sort((left, right) => compareCodePoints(
    `${left.kind}:${left.target_id}`,
    `${right.kind}:${right.target_id}`,
  ))
  .map(({ kind, target_id: targetId }) => `${kind}:${targetId}`)
  .join(',') || '-';

const navigationManifest = (map, capabilityPairs, deliveryPairs, repositoryId) => {
  const domains = [...map.domains].sort((left, right) => compareCodePoints(left.id, right.id));
  const globalBaseline = map.knowledge_baseline ?? map.project_identity?.calibration_ref;
  const referenceChecks = [
    ['/project_id', map.project_id],
    ['/knowledge_baseline', globalBaseline],
    ['/project_identity/calibration_ref', map.project_identity?.calibration_ref],
    ...map.repositories.map((repository) => (
      [`/repositories/${repository.id}/portable_locator`, repository.portable_locator]
    )),
    ...domains.flatMap((domain) => [
      [`/domains/${domain.id}/id`, domain.id],
      [`/domains/${domain.id}/parent_id`, domain.parent_id],
      ...(domain.baseline === undefined ? [] : [[`/domains/${domain.id}/baseline`, domain.baseline]]),
      ...domain.relationships.map(({ target_id: targetId }) => (
        [`/domains/${domain.id}/relationships/${targetId}`, targetId]
      )),
    ]),
    ...[...capabilityPairs.entries()].map(([id, pair]) => (
      [`/capability_frontmatters/${id}/last_verified_baseline`, pair.en.frontmatter.last_verified_baseline]
    )),
    ...[...deliveryPairs.entries()].flatMap(([id, pair]) => [
      [`/delivery_frontmatters/${id}/artifact_id`, id],
      [`/delivery_frontmatters/${id}/project_id_at_creation`, pair.en.frontmatter.project_id_at_creation],
      [`/delivery_frontmatters/${id}/current_project_id`, pair.en.frontmatter.current_project_id],
      [`/delivery_frontmatters/${id}/knowledge_baseline`, pair.en.frontmatter.knowledge_baseline],
      ...pair.en.frontmatter.domain_ids.map((domainId) => (
        [`/delivery_frontmatters/${id}/domain_ids/${domainId}`, domainId]
      )),
    ]),
  ];
  const unsafeReference = referenceChecks.find(([, value]) => (
    value !== undefined && value !== null && !isSafeReference(value)
  ));
  if (unsafeReference) {
    return failure('INDEX_REFERENCE_INVALID', unsafeReference[0], 'Generated references must be portable single-line Markdown/comment tokens.');
  }
  for (const domain of domains) {
    const pair = capabilityPairs.get(domain.id);
    const ownedHere = repositoryId === undefined
      || domain.paired_assets?.repository_id === repositoryId;
    if (domain.domain_state === 'materialized') {
      if (ownedHere && (!pair || domain.paired_assets?.en !== pair.en.locator
        || domain.paired_assets?.['zh-CN'] !== pair['zh-CN'].locator
        || domain.baseline !== pair.en.frontmatter.last_verified_baseline
        || pair.en.frontmatter.id !== domain.id)) {
        return failure('INDEX_PAIR_INVALID', `/domains/${domain.id}`, 'Materialized map ownership must match one validated capability pair.');
      }
    } else if (pair) {
      return failure('INDEX_OWNERSHIP_DUPLICATE', `/domains/${domain.id}`, 'A non-materialized domain cannot own a canonical capability pair.');
    }
  }
  for (const id of capabilityPairs.keys()) {
    if (!domains.some((domain) => domain.id === id)) {
      return failure('INDEX_OWNERSHIP_DUPLICATE', `/capability_frontmatters/${id}`, 'Capability Frontmatter has no canonical map owner.');
    }
  }

  const deliveries = [...deliveryPairs.entries()]
    .map(([id, pair]) => ({ id, pair, frontmatter: pair.en.frontmatter }))
    .sort((left, right) => compareCodePoints(left.id, right.id));
  for (const delivery of deliveries) {
    if (delivery.frontmatter.domain_ids.some((id) => !domains.some((domain) => domain.id === id))) {
      return failure('INDEX_DELIVERY_INVALID', `/delivery_frontmatters/${delivery.id}/domain_ids`, 'Delivery navigation must reference canonical domains.');
    }
    const acceptedProjectIds = new Set([map.project_id]);
    if (!acceptedProjectIds.has(delivery.frontmatter.project_id_at_creation)
      || (delivery.frontmatter.retention_tier === 'active'
        && delivery.frontmatter.current_project_id !== map.project_id)) {
      return failure('INDEX_DELIVERY_INVALID', `/delivery_frontmatters/${delivery.id}/project_id_at_creation`, 'Delivery identity must bind to the accepted current project identity.');
    }
  }

  const active = deliveries.filter(({ frontmatter }) => (
    frontmatter.retention_tier === 'active' && frontmatter.artifact_kind !== 'batch'
  ));
  const retained = deliveries.filter(({ frontmatter }) => (
    ['closed-summary', 'archive'].includes(frontmatter.retention_tier)
    && frontmatter.artifact_kind !== 'batch'
  ));
  const baselineRefs = globalBaseline ? [globalBaseline] : [];
  return ok({ active, baselineRefs, capabilityPairs, deliveries, domains, retained });
};

const headings = {
  en: {
    title: 'Project Lifecycle navigation', baseline: 'Project baseline', knowledge: 'Knowledge', delivery: 'Delivery',
    active: 'Active changes', retained: 'Closed summaries and archive locators', identity: 'Identity lineage', empty: 'None.',
  },
  'zh-CN': {
    title: 'Project Lifecycle 导航', baseline: '项目基线', knowledge: '知识', delivery: '交付',
    active: '进行中的变更', retained: '结项摘要与归档定位', identity: '身份沿革', empty: '无。',
  },
};

const knowledgeHeadings = {
  en: {
    title: 'Knowledge', entries: 'Entry domains', current: 'Current domain', body: 'Approved knowledge',
    children: 'Direct children', historical: 'Historical direct children', relationships: 'Direct relationships',
    empty: 'None.', notMaterialized: 'Not materialized.',
  },
  'zh-CN': {
    title: '知识', entries: '入口领域', current: '当前领域', body: '已批准知识',
    children: '直接子级', historical: '历史直接子级', relationships: '直接关系',
    empty: '无。', notMaterialized: '尚未物化。',
  },
};

const inlineMarkdown = (value) => value
  .replace(/\s+/gu, ' ')
  .trim()
  .replace(/[\\`*_[\]<>]/gu, '\\$&');

const renderDelivery = ({ id, pair, frontmatter }, language) => {
  const domains = [...frontmatter.domain_ids].sort(compareCodePoints).join(',');
  const currentProject = frontmatter.current_project_id ?? '-';
  const marker = `<!-- project-lifecycle:delivery artifact_id=${id} kind=${frontmatter.artifact_kind} route=${frontmatter.primary_route} retention=${frontmatter.retention_tier} project_at_creation=${frontmatter.project_id_at_creation} current_project=${currentProject} knowledge_baseline=${frontmatter.knowledge_baseline} domains=${domains} en_target=${pair.en.locator} zh_target=${pair['zh-CN'].locator} -->`;
  return `${marker}\n- [\`${id}\`](${pair[language].locator}) — kind: \`${frontmatter.artifact_kind}\`; route: \`${frontmatter.primary_route}\`; retention: \`${frontmatter.retention_tier}\`; created: \`${frontmatter.project_id_at_creation}\`; current: \`${currentProject}\`; baseline: \`${frontmatter.knowledge_baseline}\`; domains: \`${domains}\``;
};

const renderRoot = (map, manifest, language) => {
  const text = headings[language];
  const baselineLines = manifest.baselineRefs.length > 0
    ? manifest.baselineRefs.map((baseline) => `- \`${baseline}\``)
    : [`- ${text.empty}`];
  const activeLines = manifest.active.length > 0
    ? manifest.active.map((entry) => renderDelivery(entry, language)) : [`- ${text.empty}`];
  const retainedLines = manifest.retained.length > 0
    ? manifest.retained.map((entry) => renderDelivery(entry, language)) : [`- ${text.empty}`];
  return [
    NOTICE,
    `# ${map.project_identity ? inlineMarkdown(map.project_identity.label[language]) : text.title}`,
    ...(map.project_identity ? ['', inlineMarkdown(map.project_identity.purpose[language])] : []),
    '',
    `- Project ID: \`${map.project_id}\``,
    ...(map.project_identity ? [`- Calibration: \`${map.project_identity.calibration_ref}\``] : []),
    '',
    `## ${text.baseline}`,
    '',
    ...baselineLines,
    '',
    `## ${text.knowledge}`,
    '',
    `- [${text.knowledge}](${language === 'en' ? 'knowledge/INDEX-en.md' : 'knowledge/INDEX.md'})`,
    '',
    `## ${text.delivery}`,
    '',
    `- [${text.delivery}](delivery/)`,
    '',
    `## ${text.active}`,
    '',
    ...activeLines,
    '',
    `## ${text.retained}`,
    '',
    ...retainedLines,
    '',
    `## ${text.identity}`,
    '',
    `- \`${map.project_id}\` (current)`,
    '',
  ].join('\n');
};

const localizedIndexName = (language) => language === 'en' ? 'INDEX-en.md' : 'INDEX.md';

const targetForDomain = (layoutDomain, language) => {
  if (layoutDomain.has_children) return `${layoutDomain.directory}/${localizedIndexName(language)}`;
  return layoutDomain.pair?.[language] ?? null;
};

const renderDomainEntry = ({
  domain,
  layoutDomain,
  manifest,
  language,
  fromDirectory,
  portableLocator = null,
}) => {
  const frontmatter = manifest.capabilityPairs.get(domain.id)?.en.frontmatter;
  const knowledgeState = frontmatter?.knowledge_state
    ?? (domain.domain_state === 'materialized' && layoutDomain.repository_id !== null
      ? 'remote'
      : 'not-materialized');
  const target = targetForDomain(layoutDomain, language);
  const portableTarget = target && portableLocator
    ? `${portableLocator}/docs/project-lifecycle/${target}`
    : (target ? posix.relative(fromDirectory, target) : null);
  const domainLink = portableTarget
    ? `[\`domain:${domain.id}\`](${portableTarget})`
    : `\`domain:${domain.id}\``;
  return `- ${domainLink} — ${inlineMarkdown(domain.label[language])}; state: \`${domain.domain_state}\`; knowledge: \`${knowledgeState}\`; boundary: ${inlineMarkdown(domain.purpose[language])}`;
};

const renderKnowledgeRoot = (map, layout, manifest, repository, language) => {
  const text = knowledgeHeadings[language];
  const domainsById = new Map(map.domains.map((domain) => [domain.id, domain]));
  const layoutById = new Map(layout.domains.map((domain) => [domain.domain_id, domain]));
  const lines = repository.shard_entry_ids.map((id) => renderDomainEntry({
    domain: domainsById.get(id),
    layoutDomain: layoutById.get(id),
    manifest,
    language,
    fromDirectory: 'knowledge',
    portableLocator: repository.repository_id === null
      ? layout.repositories.find(({ repository_id: repositoryId }) => (
        repositoryId === layoutById.get(id).repository_id
      ))?.portable_locator
      : null,
  }));
  return [
    NOTICE,
    `# ${text.title}`,
    '',
    `## ${text.entries}`,
    '',
    ...(lines.length > 0 ? lines : [`- ${text.empty}`]),
    '',
  ].join('\n');
};

const renderDomainIndex = (map, layout, manifest, layoutDomain, language) => {
  const text = knowledgeHeadings[language];
  const domainsById = new Map(map.domains.map((domain) => [domain.id, domain]));
  const layoutById = new Map(layout.domains.map((domain) => [domain.domain_id, domain]));
  const domain = domainsById.get(layoutDomain.domain_id);
  const ownFrontmatter = manifest.capabilityPairs.get(domain.id)?.en.frontmatter;
  const ownTarget = layoutDomain.pair?.[language] ?? null;
  const ownBody = ownTarget
    ? `- [\`domain:${domain.id}\`](${ownTarget.split('/').at(-1)}) — \`${ownFrontmatter?.knowledge_state ?? 'not-materialized'}\``
    : `- ${text.notMaterialized}`;
  const active = [];
  const historical = [];
  for (const child of layoutDomain.direct_children) {
    const childDomain = domainsById.get(child.domain_id);
    const childLayout = layoutById.get(child.domain_id);
    const entry = renderDomainEntry({
      domain: childDomain,
      layoutDomain: childLayout,
      manifest,
      language,
      fromDirectory: layoutDomain.directory,
      portableLocator: child.portable_locator,
    });
    const knowledgeState = manifest.capabilityPairs.get(child.domain_id)?.en.frontmatter.knowledge_state;
    if (['merged', 'retired'].includes(childDomain.domain_state) || knowledgeState === 'superseded') historical.push(entry);
    else active.push(entry);
  }
  return [
    NOTICE,
    `# ${inlineMarkdown(domain.label[language])}`,
    '',
    `## ${text.current}`,
    '',
    `- \`domain:${domain.id}\` — state: \`${domain.domain_state}\`; boundary: ${inlineMarkdown(domain.purpose[language])}`,
    '',
    `## ${text.body}`,
    '',
    ownBody,
    '',
    `## ${text.children}`,
    '',
    ...(active.length > 0 ? active : [`- ${text.empty}`]),
    '',
    `## ${text.historical}`,
    '',
    ...(historical.length > 0 ? historical : [`- ${text.empty}`]),
    '',
    `## ${text.relationships}`,
    '',
    `- \`${relationshipToken(domain)}\``,
    '',
  ].join('\n');
};

const renderFiles = (map, layout, manifest, repositoryId) => {
  const files = [];
  for (const repository of layout.repositories) {
    for (const language of LANGUAGES) {
      files.push({
        repository_id: repository.repository_id,
        locator: language === 'en' ? 'INDEX-en.md' : 'INDEX.md',
        language,
        content: renderRoot(map, manifest, language),
        scope: 'lifecycle-root',
        domain_id: null,
      });
      files.push({
        repository_id: repository.repository_id,
        locator: `knowledge/${localizedIndexName(language)}`,
        language,
        content: renderKnowledgeRoot(map, layout, manifest, repository, language),
        scope: repository.repository_id === null ? 'governance-root' : 'repository-shard',
        domain_id: null,
      });
    }
  }
  for (const layoutDomain of layout.domains.filter(({ has_children: hasChildren }) => hasChildren)) {
    for (const language of LANGUAGES) {
      files.push({
        repository_id: layoutDomain.repository_id,
        locator: `${layoutDomain.directory}/${localizedIndexName(language)}`,
        language,
        content: renderDomainIndex(map, layout, manifest, layoutDomain, language),
        scope: 'domain',
        domain_id: layoutDomain.domain_id,
      });
    }
  }
  return files
    .filter((file) => repositoryId === undefined || file.repository_id === repositoryId)
    .sort((left, right) => compareCodePoints(left.repository_id ?? '', right.repository_id ?? '')
      || compareCodePoints(left.locator, right.locator));
};

const buildIndexes = ({
  map,
  layout: suppliedLayout,
  capability_frontmatters: capabilities = [],
  delivery_frontmatters: deliveries = [],
  repository_id: repositoryId,
} = {}) => {
  const mapValidation = validateJson('project-map', map);
  if (!mapValidation.ok) return mapValidation;
  if (!Array.isArray(capabilities) || !Array.isArray(deliveries)) {
    return failure('INDEX_INPUT_INVALID', '/', 'Frontmatter inputs must be bounded arrays.');
  }
  const capabilityPairs = pairEntries(capabilities, {
    idOf: ({ id }) => id, schema: 'capability-frontmatter', path: '/capability_frontmatters',
  });
  if (!capabilityPairs.ok) return capabilityPairs;
  const deliveryPairs = pairEntries(deliveries, {
    idOf: ({ artifact_id: id }) => id, schema: 'delivery-frontmatter', path: '/delivery_frontmatters',
  });
  if (!deliveryPairs.ok) return deliveryPairs;
  if (!(repositoryId === undefined || repositoryId === null
    || map.repositories.some(({ id }) => id === repositoryId))) {
    return failure('INDEX_INPUT_INVALID', '/repository_id', 'The active repository must be canonical map ownership.');
  }
  const manifest = navigationManifest(map, capabilityPairs.value, deliveryPairs.value, repositoryId);
  if (!manifest.ok) return manifest;
  const planned = planKnowledgeLayout({ map });
  if (!planned.ok) return planned;
  if (suppliedLayout && !same(suppliedLayout, planned.value)) {
    return failure('INDEX_LAYOUT_INVALID', '/layout', 'Index rendering requires the exact canonical layout manifest.');
  }
  for (const domain of map.domains) {
    const expectedPair = pairForDomain(planned.value, domain.id);
    if (domain.domain_state === 'materialized' && !same(expectedPair, domain.paired_assets)) {
      return failure('INDEX_LAYOUT_INVALID', `/domains/${domain.id}/paired_assets`, 'Materialized asset locators must match the canonical recursive layout.');
    }
  }
  const files = renderFiles(map, planned.value, manifest.value, repositoryId);
  const selectedRepositoryId = repositoryId === undefined ? null : repositoryId;
  const rootEn = files.find(({ repository_id: id, locator }) => id === selectedRepositoryId && locator === 'INDEX-en.md');
  const rootZh = files.find(({ repository_id: id, locator }) => id === selectedRepositoryId && locator === 'INDEX.md');
  return ok({
    layout: planned.value,
    files,
    en: rootEn.content,
    'zh-CN': rootZh.content,
    machine: {
      project_id: map.project_id,
      baseline_refs: manifest.value.baselineRefs,
      domain_ids: manifest.value.domains.map(({ id }) => id),
      active_delivery_ids: manifest.value.active.map(({ id }) => id),
      retained_delivery_ids: manifest.value.retained.map(({ id }) => id),
      identity_ids: [map.project_id],
    },
  });
};

export const renderKnowledgeIndexes = (input = {}) => buildIndexes(input);

export const generateIndexes = (input = {}) => buildIndexes(input);

/**
 * Collects only bounded Frontmatter prefixes from a trusted lifecycle root and
 * delegates all navigation semantics to the pure generator above.
 */
export const generateIndexesFromRoot = async ({
  map,
  lifecycleRoot: rootValue,
  overlays = {},
  repository_id: repositoryId = null,
} = {}) => {
  const mapValidation = validateJson('project-map', map);
  if (!mapValidation.ok) return mapValidation;
  if (typeof rootValue !== 'string' || !isAbsolute(rootValue) || !record(overlays)) {
    return failure('INDEX_INPUT_INVALID', '/', 'An absolute lifecycle root and bounded overlays are required.');
  }
  let lifecycleRoot;
  try {
    const lexical = resolve(rootValue);
    const state = await lstat(lexical);
    lifecycleRoot = await realpath(lexical);
    if (!state.isDirectory() || state.isSymbolicLink()) throw new Error('Regular lifecycle root required.');
  } catch {
    return failure('INDEX_ROOT_INVALID', '/', 'A bounded regular lifecycle root is required.');
  }
  const overlayMap = new Map(Object.entries(overlays));
  const capabilities = [];
  const deliveries = [];
  try {
    for (const domain of map.domains) {
      if (domain.domain_state !== 'materialized'
        || domain.paired_assets?.repository_id !== repositoryId) continue;
      for (const language of LANGUAGES) {
        const locator = domain.paired_assets?.[language];
        capabilities.push({
          language,
          locator,
          frontmatter: await readBoundedFrontmatter(
            lifecycleRoot,
            locator,
            'capability-frontmatter',
            overlayMap,
          ),
        });
      }
    }

    const deliveryRoot = join(lifecycleRoot, 'delivery');
    let names = [];
    try {
      if (repositoryId !== null) throw Object.assign(new Error('Repository shards do not own delivery metadata.'), { code: 'ENOENT' });
      const deliveryState = await lstat(deliveryRoot);
      const realDeliveryRoot = await realpath(deliveryRoot);
      if (!deliveryState.isDirectory() || deliveryState.isSymbolicLink() || !inside(lifecycleRoot, realDeliveryRoot)) {
        throw Object.assign(new Error('Delivery root escapes lifecycle root.'), { code: 'PATH_SYMLINK_ESCAPE' });
      }
      names = (await readdir(realDeliveryRoot)).filter((name) => name.endsWith('.md')).sort(compareCodePoints);
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
    }
    for (const name of names) {
      const locator = `delivery/${name}`;
      deliveries.push({
        language: name.endsWith('-en.md') ? 'en' : 'zh-CN',
        locator,
        frontmatter: await readBoundedFrontmatter(
          lifecycleRoot,
          locator,
          'delivery-frontmatter',
          overlayMap,
        ),
      });
    }
    for (const locator of overlayMap.keys()) {
      if (!locator.startsWith('delivery/') || !locator.endsWith('.md')
        || names.includes(basename(locator))) continue;
      deliveries.push({
        language: locator.endsWith('-en.md') ? 'en' : 'zh-CN',
        locator,
        frontmatter: await readBoundedFrontmatter(
          lifecycleRoot,
          locator,
          'delivery-frontmatter',
          overlayMap,
        ),
      });
    }
  } catch (error) {
    return failure(error?.code ?? 'INDEX_FRONTMATTER_INVALID', '/', 'Navigation Frontmatter could not be collected safely.');
  }
  return generateIndexes({
    map,
    capability_frontmatters: capabilities,
    delivery_frontmatters: deliveries,
    repository_id: repositoryId,
  });
};
