export const ERROR_CODES = Object.freeze({
  SCHEMA_INVALID: 'SCHEMA_INVALID',
  KNOWLEDGE_LAYOUT_MIGRATION_REQUIRED: 'KNOWLEDGE_LAYOUT_MIGRATION_REQUIRED',
  ID_DUPLICATE: 'ID_DUPLICATE',
  REFERENCE_MISSING: 'REFERENCE_MISSING',
  STATE_REQUIREMENT_MISSING: 'STATE_REQUIREMENT_MISSING',
  VOCAB_UNKNOWN_KIND: 'VOCAB_UNKNOWN_KIND',
  VOCAB_UNKNOWN_VALUE: 'VOCAB_UNKNOWN_VALUE',
});

export const createError = (code, path, message) => ({ code, path, message });
