import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';

import { generateIndexes, generateIndexesFromRoot } from '../../scripts/knowledge/generate-indexes.mjs';

const map = {
  schema_version: 1,
  project_id: 'sample-project',
  project_identity: {
    label: { en: 'Sample project', 'zh-CN': '示例项目' },
    purpose: { en: 'Routes accepted work.', 'zh-CN': '路由已验收工作。' },
    calibration_ref: 'calibration:sample-project',
  },
  identity_lineage: [],
  repositories: [],
  constraints: [],
  domains: [
    {
      id: 'alpha-workspace', kind: 'capability',
      label: { en: 'Alpha workspace', 'zh-CN': 'Alpha 工作区' },
      purpose: { en: 'Owns alpha.', 'zh-CN': '负责 Alpha。' },
      domain_state: 'materialized',
      scope: { includes: ['alpha'], excludes: [] }, parent_id: null,
      relationships: [{ kind: 'depends_on', target_id: 'zeta-workspace' }],
      evidence_refs: ['repo:README.md'], known_gaps: [],
      paired_assets: { en: 'knowledge/alpha-workspace-en.md', 'zh-CN': 'knowledge/alpha-workspace.md' },
      baseline: 'baseline-2',
    },
    {
      id: 'zeta-workspace', kind: 'capability',
      label: { en: 'Zeta workspace', 'zh-CN': 'Zeta 工作区' },
      purpose: { en: 'Owns zeta.', 'zh-CN': '负责 Zeta。' },
      domain_state: 'confirmed',
      scope: { includes: ['zeta'], excludes: [] }, parent_id: null,
      relationships: [], evidence_refs: ['repo:README.md'], known_gaps: [],
    },
  ],
};

const capabilityPair = [
  {
    language: 'en', locator: 'knowledge/alpha-workspace-en.md',
    frontmatter: {
      id: 'alpha-workspace', knowledge_state: 'current', paired_asset: 'alpha-workspace.md',
      last_verified_baseline: 'baseline-2', implementation_refs: ['repo:src/alpha'], verification_refs: ['repo:test/alpha'],
    },
  },
  {
    language: 'zh-CN', locator: 'knowledge/alpha-workspace.md',
    frontmatter: {
      id: 'alpha-workspace', knowledge_state: 'current', paired_asset: 'alpha-workspace.md',
      last_verified_baseline: 'baseline-2', implementation_refs: ['repo:src/alpha'], verification_refs: ['repo:test/alpha'],
    },
  },
];

const delivery = (artifactId, artifactKind, retentionTier, language, locator, domainIds = ['alpha-workspace']) => ({
  language,
  locator,
  frontmatter: {
    schema_version: 1,
    artifact_id: artifactId,
    artifact_kind: artifactKind,
    primary_route: 'PRD_DELIVERY',
    project_id_at_creation: 'sample-project',
    ...(retentionTier === 'active' ? { current_project_id: 'sample-project' } : {}),
    domain_ids: domainIds,
    knowledge_baseline: 'baseline-2',
    relationships: { feedback_ids: [], prd_ids: [], legacy_artifact_refs: [] },
    retention_tier: retentionTier,
    reclassified_from_refs: [],
    obligations: [],
  },
});

const pairedDelivery = (id, kind, tier, stem, domainIds) => [
  delivery(id, kind, tier, 'en', `delivery/${stem}-en.md`, domainIds),
  delivery(id, kind, tier, 'zh-CN', `delivery/${stem}.md`, domainIds),
];

test('generates paired low-noise views from machine metadata only', () => {
  const deliveries = [
    ...pairedDelivery('prd-alpha-refresh', 'prd', 'active', 'prd-alpha-refresh'),
    ...pairedDelivery('closure-alpha-v1', 'closure-summary', 'closed-summary', 'closure-alpha-v1'),
    ...pairedDelivery('report-alpha-v0', 'test-report', 'archive', 'report-alpha-v0'),
    ...pairedDelivery('batch-alpha-001', 'batch', 'active', 'batch-alpha-001'),
  ];
  const result = generateIndexes({ map, capability_frontmatters: capabilityPair, delivery_frontmatters: deliveries });

  assert.equal(result.ok, true);
  for (const source of [result.value.en, result.value['zh-CN']]) {
    assert.match(source, /^<!-- Generated by Project Lifecycle from project-map and validated Frontmatter; do not edit\. -->/);
    assert.match(source, /baseline-2/);
    assert.match(source, /calibration:sample-project/);
    assert.match(source, /alpha-workspace/);
    assert.match(source, /zeta-workspace/);
    assert.match(source, /depends_on:zeta-workspace/);
    assert.match(source, /prd-alpha-refresh/);
    assert.match(source, /closure-alpha-v1/);
    assert.match(source, /report-alpha-v0/);
    assert.match(source, /knowledge_state=current/);
    assert.match(source, /route=PRD_DELIVERY/);
    assert.match(source, /project_at_creation=sample-project/);
    assert.match(source, /current_project=sample-project/);
    assert.match(source, /knowledge_baseline=baseline-2/);
    assert.doesNotMatch(source, /batch-alpha-001/);
    assert.doesNotMatch(source, /npm test|command log|fact prose|Canonical owner/);
    assert.equal((source.match(/artifact_id=prd-alpha-refresh/g) ?? []).length, 1);
  }
  assert.ok(result.value.en.indexOf('alpha-workspace') < result.value.en.indexOf('zeta-workspace'));
  assert.deepEqual(result.value.machine, {
    project_id: 'sample-project',
    baseline_refs: ['baseline-2', 'calibration:sample-project'],
    domain_ids: ['alpha-workspace', 'zeta-workspace'],
    active_delivery_ids: ['prd-alpha-refresh'],
    retained_delivery_ids: ['closure-alpha-v1', 'report-alpha-v0'],
    identity_ids: ['sample-project'],
  });
});

test('rejects missing mirrors, mismatched machine fields, duplicate ownership, and unsafe targets', () => {
  const cases = [
    { capabilities: capabilityPair.slice(0, 1), deliveries: [], code: 'INDEX_PAIR_INVALID' },
    {
      capabilities: capabilityPair.map((entry, index) => index === 1
        ? { ...entry, frontmatter: { ...entry.frontmatter, knowledge_state: 'proposed' } }
        : entry),
      deliveries: [], code: 'INDEX_PAIR_INVALID',
    },
    {
      capabilities: [...capabilityPair, ...capabilityPair.map((entry) => ({ ...entry }))],
      deliveries: [], code: 'INDEX_OWNERSHIP_DUPLICATE',
    },
    {
      capabilities: capabilityPair,
      deliveries: pairedDelivery('prd-alpha-refresh', 'prd', 'active', '../escape'),
      code: 'INDEX_TARGET_INVALID',
    },
    {
      capabilities: capabilityPair,
      deliveries: pairedDelivery('prd-alpha-refresh', 'prd', 'active', 'bad)target'),
      code: 'INDEX_TARGET_INVALID',
    },
    {
      capabilities: capabilityPair,
      deliveries: pairedDelivery('prd-alpha-refresh', 'prd', 'active', 'bad#target'),
      code: 'INDEX_TARGET_INVALID',
    },
  ];
  for (const entry of cases) {
    const result = generateIndexes({ map, capability_frontmatters: entry.capabilities, delivery_frontmatters: entry.deliveries });
    assert.equal(result.ok, false);
    assert.equal(result.errors[0].code, entry.code);
  }
});

test('is byte deterministic regardless of caller ordering and uses code-point ordering', () => {
  const deliveries = [
    ...pairedDelivery('prd-zeta', 'prd', 'active', 'prd-zeta', ['zeta-workspace']),
    ...pairedDelivery('prd-alpha', 'prd', 'active', 'prd-alpha'),
  ];
  const forward = generateIndexes({ map, capability_frontmatters: capabilityPair, delivery_frontmatters: deliveries });
  const reverse = generateIndexes({
    map,
    capability_frontmatters: [...capabilityPair].reverse().map((entry, index) => index === 0 ? {
      ...entry,
      frontmatter: Object.fromEntries(Object.entries(entry.frontmatter).reverse()),
    } : entry),
    delivery_frontmatters: [...deliveries].reverse(),
  });
  assert.equal(forward.ok, true);
  assert.equal(reverse.ok, true);
  assert.deepEqual(reverse.value, forward.value);
});

test('rejects delivery metadata bound to a foreign project identity', () => {
  const deliveries = pairedDelivery('prd-alpha', 'prd', 'active', 'prd-alpha').map((entry) => ({
    ...entry,
    frontmatter: {
      ...entry.frontmatter,
      project_id_at_creation: 'foreign-project',
      current_project_id: 'foreign-project',
    },
  }));
  const result = generateIndexes({ map, capability_frontmatters: capabilityPair, delivery_frontmatters: deliveries });
  assert.equal(result.ok, false);
  assert.equal(result.errors[0].code, 'INDEX_DELIVERY_INVALID');
});

test('collects CRLF Frontmatter through the exact bounded delimiter', async (context) => {
  const root = await mkdtemp(join(tmpdir(), 'project-lifecycle-index-crlf-'));
  context.after(() => rm(root, { recursive: true, force: true }));
  await mkdir(join(root, 'knowledge'), { recursive: true });
  const source = (frontmatter) => `---\n${Object.entries(frontmatter).map(([key, value]) => (
    Array.isArray(value)
      ? `${key}:\n${value.map((item) => `  - ${item}`).join('\n')}`
      : `${key}: ${value}`
  )).join('\n')}\n---\n\n# BODY MUST STAY OUT OF THE INDEX\n`.replaceAll('\n', '\r\n');
  for (const entry of capabilityPair) {
    await writeFile(join(root, entry.locator), source(entry.frontmatter));
  }

  const result = await generateIndexesFromRoot({ map, lifecycleRoot: root });

  assert.equal(result.ok, true, JSON.stringify(result));
  assert.doesNotMatch(result.value.en, /BODY MUST STAY OUT/);
});

test('ships paired index templates as exact output of the inert validated map', async () => {
  const templateMap = JSON.parse(await readFile(
    new URL('../../skills/maintain-project-knowledge/assets/project-map.json', import.meta.url),
    'utf8',
  ));
  const generated = generateIndexes({ map: templateMap });
  assert.equal(generated.ok, true);
  assert.equal(generated.value.en, await readFile(
    new URL('../../skills/maintain-project-knowledge/assets/INDEX-en.md', import.meta.url),
    'utf8',
  ));
  assert.equal(generated.value['zh-CN'], await readFile(
    new URL('../../skills/maintain-project-knowledge/assets/INDEX.md', import.meta.url),
    'utf8',
  ));
});
