import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, rm, unlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';

import {
  generateIndexes,
  generateIndexesFromRoot,
  renderKnowledgeIndexes,
} from '../../scripts/knowledge/generate-indexes.mjs';
import { planKnowledgeLayout } from '../../scripts/knowledge/layout-planner.mjs';

const map = {
  schema_version: 2,
  project_id: 'sample-project',
  knowledge_baseline: 'baseline:release/3#accepted',
  project_identity: {
    label: { en: 'Sample project', 'zh-CN': '示例项目' },
    purpose: { en: 'Routes accepted work.', 'zh-CN': '路由已验收工作。' },
    calibration_ref: 'calibration:sample-project',
  },
  identity_lineage: [],
  repositories: [],
  constraints: [],
  domains: [
    {
      id: 'alpha-workspace', kind: 'capability',
      label: { en: 'Alpha workspace', 'zh-CN': 'Alpha 工作区' },
      purpose: { en: 'Owns alpha.', 'zh-CN': '负责 Alpha。' },
      domain_state: 'materialized',
      scope: { includes: ['alpha'], excludes: [] }, parent_id: null,
      relationships: [{ kind: 'depends_on', target_id: 'zeta-workspace' }],
      evidence_refs: ['repo:README.md'], known_gaps: [],
      paired_assets: { repository_id: null, en: 'knowledge/alpha-workspace-en.md', 'zh-CN': 'knowledge/alpha-workspace.md' },
      baseline: 'baseline-2',
    },
    {
      id: 'zeta-workspace', kind: 'capability',
      label: { en: 'Zeta workspace', 'zh-CN': 'Zeta 工作区' },
      purpose: { en: 'Owns zeta.', 'zh-CN': '负责 Zeta。' },
      domain_state: 'confirmed',
      scope: { includes: ['zeta'], excludes: [] }, parent_id: null,
      relationships: [], evidence_refs: ['repo:README.md'], known_gaps: [],
    },
  ],
};

const capabilityPair = [
  {
    language: 'en', locator: 'knowledge/alpha-workspace-en.md',
    frontmatter: {
      id: 'alpha-workspace', knowledge_state: 'current', paired_asset: 'alpha-workspace.md',
      last_verified_baseline: 'baseline-2', implementation_refs: ['repo:src/alpha'], verification_refs: ['repo:test/alpha'],
    },
  },
  {
    language: 'zh-CN', locator: 'knowledge/alpha-workspace.md',
    frontmatter: {
      id: 'alpha-workspace', knowledge_state: 'current', paired_asset: 'alpha-workspace.md',
      last_verified_baseline: 'baseline-2', implementation_refs: ['repo:src/alpha'], verification_refs: ['repo:test/alpha'],
    },
  },
];

const delivery = (artifactId, artifactKind, retentionTier, language, locator, domainIds = ['alpha-workspace']) => ({
  language,
  locator,
  frontmatter: {
    schema_version: 1,
    artifact_id: artifactId,
    artifact_kind: artifactKind,
    primary_route: 'PRD_DELIVERY',
    project_id_at_creation: 'sample-project',
    ...(retentionTier === 'active' ? { current_project_id: 'sample-project' } : {}),
    domain_ids: domainIds,
    knowledge_baseline: 'baseline-2',
    relationships: { feedback_ids: [], prd_ids: [], legacy_artifact_refs: [] },
    retention_tier: retentionTier,
    reclassified_from_refs: [],
    obligations: [],
  },
});

const pairedDelivery = (id, kind, tier, stem, domainIds) => [
  delivery(id, kind, tier, 'en', `delivery/${stem}-en.md`, domainIds),
  delivery(id, kind, tier, 'zh-CN', `delivery/${stem}.md`, domainIds),
];

test('generates bounded root and Knowledge views from machine metadata only', () => {
  const deliveries = [
    ...pairedDelivery('prd-alpha-refresh', 'prd', 'active', 'prd-alpha-refresh'),
    ...pairedDelivery('closure-alpha-v1', 'closure-summary', 'closed-summary', 'closure-alpha-v1'),
    ...pairedDelivery('report-alpha-v0', 'test-report', 'archive', 'report-alpha-v0'),
    ...pairedDelivery('batch-alpha-001', 'batch', 'active', 'batch-alpha-001'),
  ];
  const result = generateIndexes({ map, capability_frontmatters: capabilityPair, delivery_frontmatters: deliveries });

  assert.equal(result.ok, true);
  for (const source of [result.value.en, result.value['zh-CN']]) {
    assert.match(source, /^<!-- Generated by Project Lifecycle from project-map and validated Frontmatter; do not edit\. -->/);
    assert.match(source, /baseline:release\/3#accepted/);
    assert.match(source, /calibration:sample-project/);
    assert.match(source, /prd-alpha-refresh/);
    assert.match(source, /closure-alpha-v1/);
    assert.match(source, /report-alpha-v0/);
    assert.match(source, /route=PRD_DELIVERY/);
    assert.match(source, /project_at_creation=sample-project/);
    assert.match(source, /current_project=sample-project/);
    assert.match(source, /knowledge_baseline=baseline-2/);
    const baselineSection = /## (?:Project baseline|项目基线)\n\n([\s\S]*?)\n\n##/u.exec(source)?.[1];
    assert.equal(baselineSection, '- `baseline:release/3#accepted`');
    assert.doesNotMatch(source, /batch-alpha-001/);
    assert.doesNotMatch(source, /npm test|command log|fact prose|Canonical owner/);
    assert.equal((source.match(/artifact_id=prd-alpha-refresh/g) ?? []).length, 1);
  }
  assert.doesNotMatch(result.value.en, /project-lifecycle:domain|Domain entry points/);
  const knowledgeEn = result.value.files.find(({ repository_id: repositoryId, locator }) => (
    repositoryId === null && locator === 'knowledge/INDEX-en.md'
  )).content;
  assert.match(knowledgeEn, /alpha-workspace/);
  assert.match(knowledgeEn, /zeta-workspace/);
  assert.match(knowledgeEn, /knowledge: `current`/);
  assert.ok(knowledgeEn.indexOf('alpha-workspace') < knowledgeEn.indexOf('zeta-workspace'));
  assert.deepEqual(result.value.machine, {
    project_id: 'sample-project',
    baseline_refs: ['baseline:release/3#accepted'],
    domain_ids: ['alpha-workspace', 'zeta-workspace'],
    active_delivery_ids: ['prd-alpha-refresh'],
    retained_delivery_ids: ['closure-alpha-v1', 'report-alpha-v0'],
    identity_ids: ['sample-project'],
  });
});

test('renders lifecycle, Knowledge, and domain indexes with direct-child-only expansion', () => {
  const hierarchicalMap = JSON.parse(JSON.stringify(map));
  hierarchicalMap.domains = [
    {
      ...hierarchicalMap.domains[0],
      id: 'runtime',
      label: { en: 'Runtime', 'zh-CN': '运行时' },
      purpose: { en: 'Owns runtime.', 'zh-CN': '负责运行时。' },
      scope: { includes: ['alpha', 'loop', 'tools'], excludes: [] },
      relationships: [{ kind: 'depends_on', target_id: 'zeta-workspace' }],
      paired_assets: {
        repository_id: null,
        en: 'knowledge/runtime/runtime-en.md',
        'zh-CN': 'knowledge/runtime/runtime.md',
      },
    },
    {
      ...hierarchicalMap.domains[0],
      id: 'loop',
      label: { en: 'Loop', 'zh-CN': '循环' },
      purpose: { en: 'Owns loop.', 'zh-CN': '负责循环。' },
      scope: { includes: ['loop', 'tools'], excludes: [] },
      parent_id: 'runtime',
      relationships: [],
      paired_assets: {
        repository_id: null,
        en: 'knowledge/runtime/loop/loop-en.md',
        'zh-CN': 'knowledge/runtime/loop/loop.md',
      },
    },
    {
      ...hierarchicalMap.domains[0],
      id: 'tools',
      label: { en: 'Tools', 'zh-CN': '工具' },
      purpose: { en: 'Owns tools.', 'zh-CN': '负责工具。' },
      scope: { includes: ['tools'], excludes: [] },
      parent_id: 'loop',
      relationships: [],
      paired_assets: {
        repository_id: null,
        en: 'knowledge/runtime/loop/tools-en.md',
        'zh-CN': 'knowledge/runtime/loop/tools.md',
      },
    },
    hierarchicalMap.domains[1],
  ].sort((left, right) => left.id < right.id ? -1 : left.id > right.id ? 1 : 0);
  const pairs = hierarchicalMap.domains
    .filter(({ domain_state: state }) => state === 'materialized')
    .flatMap((domain) => ['en', 'zh-CN'].map((language) => ({
      language,
      locator: domain.paired_assets[language],
      frontmatter: {
        id: domain.id,
        knowledge_state: 'current',
        paired_asset: domain.paired_assets['zh-CN'].split('/').at(-1),
        last_verified_baseline: domain.baseline,
        implementation_refs: [`repo:src/${domain.id}`],
        verification_refs: [`repo:test/${domain.id}`],
      },
    })));
  const planned = planKnowledgeLayout({ map: hierarchicalMap });
  assert.equal(planned.ok, true, JSON.stringify(planned));

  const result = renderKnowledgeIndexes({
    map: hierarchicalMap,
    layout: planned.value,
    capability_frontmatters: pairs,
  });

  assert.equal(result.ok, true, JSON.stringify(result));
  const file = (locator) => result.value.files.find((entry) => (
    entry.repository_id === null && entry.locator === locator
  )).content;
  assert.doesNotMatch(file('INDEX-en.md'), /domain:runtime|domain:loop|domain:tools/);
  assert.match(file('knowledge/INDEX-en.md'), /domain:runtime/);
  assert.doesNotMatch(file('knowledge/INDEX-en.md'), /domain:loop|domain:tools/);
  assert.match(file('knowledge/INDEX-en.md'), /\(runtime\/INDEX-en\.md\)/);
  assert.match(file('knowledge/runtime/INDEX-en.md'), /domain:loop/);
  assert.doesNotMatch(file('knowledge/runtime/INDEX-en.md'), /domain:tools/);
  assert.match(file('knowledge/runtime/INDEX-en.md'), /\(loop\/INDEX-en\.md\)/);
  assert.doesNotMatch(file('knowledge/runtime/INDEX-en.md'), /\(knowledge\/runtime\/loop/);
  assert.match(file('knowledge/runtime/INDEX-en.md'), /depends_on:zeta-workspace/);
  assert.match(file('knowledge/runtime/loop/INDEX-en.md'), /domain:tools/);
});

test('bounds repository shards and renders portable cross-repository children', () => {
  const makeDomain = (id, parentId, state, scope, repositoryId = null) => ({
    id,
    kind: 'capability',
    label: { en: id, 'zh-CN': id },
    purpose: { en: `Owns ${id}.`, 'zh-CN': `负责 ${id}。` },
    domain_state: state,
    scope: { includes: scope, excludes: [] },
    parent_id: parentId,
    relationships: [],
    evidence_refs: [`repo:${id}`],
    known_gaps: [],
    ...(state === 'materialized' ? {
      baseline: `baseline:${id}`,
      paired_assets: {
        repository_id: repositoryId,
        en: id === 'runtime' ? 'knowledge/runtime/runtime-en.md' : 'knowledge/api/api-en.md',
        'zh-CN': id === 'runtime' ? 'knowledge/runtime/runtime.md' : 'knowledge/api/api.md',
      },
    } : {}),
    ...(['retired', 'merged'].includes(state) ? { retirement_reason: 'Replaced by API.' } : {}),
  });
  const crossMap = {
    ...JSON.parse(JSON.stringify(map)),
    repositories: [{
      id: 'backend',
      purpose: { en: 'Owns backend knowledge.', 'zh-CN': '负责后端知识。' },
      portable_locator: 'github:example/backend',
      integration_ref: 'refs/heads/main',
      domain_ids: ['api', 'archive', 'storage'],
      knowledge_asset_locators: ['knowledge/api/api-en.md', 'knowledge/api/api.md'],
      accepted_revision: 'revision:backend',
    }],
    domains: [
      makeDomain('api', 'runtime', 'materialized', ['api', 'archive', 'portal', 'storage'], 'backend'),
      makeDomain('archive', 'storage', 'confirmed', ['archive'], 'backend'),
      {
        ...makeDomain('portal', 'api', 'materialized', ['portal']),
        paired_assets: {
          repository_id: null,
          en: 'knowledge/portal-en.md',
          'zh-CN': 'knowledge/portal.md',
        },
      },
      makeDomain('runtime', null, 'materialized', ['api', 'archive', 'portal', 'runtime', 'storage']),
      { ...makeDomain('storage', 'api', 'merged', ['archive', 'storage'], 'backend'), successor_id: 'api' },
    ],
  };
  const pairs = crossMap.domains
    .filter(({ domain_state: state }) => state === 'materialized')
    .flatMap((domain) => ['en', 'zh-CN'].map((language) => ({
      language,
      locator: domain.paired_assets[language],
      frontmatter: {
        id: domain.id,
        knowledge_state: 'current',
        paired_asset: domain.paired_assets['zh-CN'].split('/').at(-1),
        last_verified_baseline: domain.baseline,
        implementation_refs: [`repo:src/${domain.id}`],
        verification_refs: [`repo:test/${domain.id}`],
      },
    })));

  const result = generateIndexes({ map: crossMap, capability_frontmatters: pairs });

  assert.equal(result.ok, true, JSON.stringify(result));
  const file = (repositoryId, locator) => result.value.files.find((entry) => (
    entry.repository_id === repositoryId && entry.locator === locator
  )).content;
  assert.match(file(null, 'knowledge/INDEX-en.md'), /domain:runtime/);
  assert.doesNotMatch(file(null, 'knowledge/INDEX-en.md'), /domain:api|domain:storage/);
  assert.match(file('backend', 'knowledge/INDEX-en.md'), /domain:api/);
  assert.doesNotMatch(file('backend', 'knowledge/INDEX-en.md'), /domain:runtime|domain:storage/);
  assert.doesNotMatch(file('backend', 'INDEX-en.md'), /\]\(delivery\/\)/);
  assert.match(file(null, 'knowledge/runtime/INDEX-en.md'), /github:example\/backend\/docs\/project-lifecycle\/knowledge\/api\/INDEX-en\.md/);
  const apiIndex = file('backend', 'knowledge/api/INDEX-en.md');
  assert.match(apiIndex, /project:sample-project\/docs\/project-lifecycle\/knowledge\/portal-en\.md[\s\S]*knowledge: `remote`/);
  assert.match(apiIndex, /## Historical direct children[\s\S]*domain:storage/);
  assert.match(apiIndex, /domain:storage[\s\S]*successor: `domain:api`/);
  assert.doesNotMatch(apiIndex, /domain:storage`\]\(storage\/INDEX-en\.md\)/);
  assert.doesNotMatch(/## Direct children[\s\S]*?## Historical direct children/u.exec(apiIndex)[0], /domain:storage/);
});

test('rejects missing mirrors, mismatched machine fields, duplicate ownership, and unsafe targets', () => {
  const cases = [
    { capabilities: capabilityPair.slice(0, 1), deliveries: [], code: 'INDEX_PAIR_INVALID' },
    {
      capabilities: capabilityPair.map((entry, index) => index === 1
        ? { ...entry, frontmatter: { ...entry.frontmatter, knowledge_state: 'proposed' } }
        : entry),
      deliveries: [], code: 'INDEX_PAIR_INVALID',
    },
    {
      capabilities: [...capabilityPair, ...capabilityPair.map((entry) => ({ ...entry }))],
      deliveries: [], code: 'INDEX_OWNERSHIP_DUPLICATE',
    },
    {
      capabilities: capabilityPair,
      deliveries: pairedDelivery('prd-alpha-refresh', 'prd', 'active', '../escape'),
      code: 'INDEX_TARGET_INVALID',
    },
    {
      capabilities: capabilityPair,
      deliveries: pairedDelivery('prd-alpha-refresh', 'prd', 'active', 'bad)target'),
      code: 'INDEX_TARGET_INVALID',
    },
    {
      capabilities: capabilityPair,
      deliveries: pairedDelivery('prd-alpha-refresh', 'prd', 'active', 'bad#target'),
      code: 'INDEX_TARGET_INVALID',
    },
    {
      capabilities: capabilityPair,
      deliveries: pairedDelivery('prd-alpha-refresh', 'prd', 'active', 'bad--comment'),
      code: 'INDEX_TARGET_INVALID',
    },
  ];
  for (const entry of cases) {
    const result = generateIndexes({ map, capability_frontmatters: entry.capabilities, delivery_frontmatters: entry.deliveries });
    assert.equal(result.ok, false);
    assert.equal(result.errors[0].code, entry.code);
  }
});

test('is byte deterministic regardless of caller ordering and uses code-point ordering', () => {
  const deliveries = [
    ...pairedDelivery('prd-zeta', 'prd', 'active', 'prd-zeta', ['zeta-workspace']),
    ...pairedDelivery('prd-alpha', 'prd', 'active', 'prd-alpha'),
  ];
  const forward = generateIndexes({ map, capability_frontmatters: capabilityPair, delivery_frontmatters: deliveries });
  const reverse = generateIndexes({
    map,
    capability_frontmatters: [...capabilityPair].reverse().map((entry, index) => index === 0 ? {
      ...entry,
      frontmatter: Object.fromEntries(Object.entries(entry.frontmatter).reverse()),
    } : entry),
    delivery_frontmatters: [...deliveries].reverse(),
  });
  assert.equal(forward.ok, true);
  assert.equal(reverse.ok, true);
  assert.deepEqual(reverse.value, forward.value);
});

test('rejects delivery metadata bound to a foreign project identity', () => {
  const deliveries = pairedDelivery('prd-alpha', 'prd', 'active', 'prd-alpha').map((entry) => ({
    ...entry,
    frontmatter: {
      ...entry.frontmatter,
      project_id_at_creation: 'foreign-project',
      current_project_id: 'foreign-project',
    },
  }));
  const result = generateIndexes({ map, capability_frontmatters: capabilityPair, delivery_frontmatters: deliveries });
  assert.equal(result.ok, false);
  assert.equal(result.errors[0].code, 'INDEX_DELIVERY_INVALID');
});

test('rejects unsafe generated reference values before Markdown or comment interpolation', () => {
  const clone = (value) => JSON.parse(JSON.stringify(value));
  const cases = [
    () => {
      const unsafeMap = clone(map);
      unsafeMap.knowledge_baseline = 'global\u0001baseline';
      return { map: unsafeMap, capability_frontmatters: capabilityPair, delivery_frontmatters: [] };
    },
    () => {
      const unsafeMap = clone(map);
      unsafeMap.project_identity.calibration_ref = 'calibration:\nunsafe';
      return { map: unsafeMap, capability_frontmatters: capabilityPair, delivery_frontmatters: [] };
    },
    () => {
      const unsafeMap = clone(map);
      unsafeMap.domains[0].baseline = 'baseline`unsafe';
      const capabilities = clone(capabilityPair);
      for (const entry of capabilities) entry.frontmatter.last_verified_baseline = 'baseline`unsafe';
      return { map: unsafeMap, capability_frontmatters: capabilities, delivery_frontmatters: [] };
    },
    () => {
      const deliveries = pairedDelivery('prd-alpha', 'prd', 'active', 'prd-alpha');
      for (const entry of deliveries) entry.frontmatter.knowledge_baseline = 'baseline-->unsafe';
      return { map, capability_frontmatters: capabilityPair, delivery_frontmatters: deliveries };
    },
    () => {
      const unsafeMap = clone(map);
      unsafeMap.knowledge_baseline = 'repo:https://user:secret@example.test/private';
      return { map: unsafeMap, capability_frontmatters: capabilityPair, delivery_frontmatters: [] };
    },
  ];
  for (const build of cases) {
    const result = generateIndexes(build());
    assert.equal(result.ok, false);
    assert.equal(result.errors[0].code, 'INDEX_REFERENCE_INVALID');
  }
});

test('collects CRLF Frontmatter through the exact bounded delimiter', async (context) => {
  const root = await mkdtemp(join(tmpdir(), 'project-lifecycle-index-crlf-'));
  context.after(() => rm(root, { recursive: true, force: true }));
  await mkdir(join(root, 'knowledge'), { recursive: true });
  const source = (frontmatter) => `---\n${Object.entries(frontmatter).map(([key, value]) => (
    Array.isArray(value)
      ? `${key}:\n${value.map((item) => `  - ${item}`).join('\n')}`
      : `${key}: ${value}`
  )).join('\n')}\n---\n\n# BODY MUST STAY OUT OF THE INDEX\n`.replaceAll('\n', '\r\n');
  for (const entry of capabilityPair) {
    await writeFile(join(root, entry.locator), source(entry.frontmatter));
  }

  const result = await generateIndexesFromRoot({ map, lifecycleRoot: root });

  assert.equal(result.ok, true, JSON.stringify(result));
  assert.doesNotMatch(result.value.en, /BODY MUST STAY OUT/);
});

test('ignores only the exact generated alignment projection filenames in delivery discovery', async (context) => {
  const root = await mkdtemp(join(tmpdir(), 'project-lifecycle-index-alignment-'));
  context.after(() => rm(root, { recursive: true, force: true }));
  await mkdir(join(root, 'knowledge'), { recursive: true });
  await mkdir(join(root, 'delivery'), { recursive: true });
  const source = (frontmatter) => `---\n${Object.entries(frontmatter).map(([key, value]) => (
    Array.isArray(value)
      ? `${key}:\n${value.map((item) => `  - ${item}`).join('\n')}`
      : `${key}: ${value}`
  )).join('\n')}\n---\n`;
  for (const entry of capabilityPair) await writeFile(join(root, entry.locator), source(entry.frontmatter));
  const generatedNotice = '<!-- Generated by Project Lifecycle from validated active alignment state; do not edit. -->\n';
  await writeFile(join(root, 'delivery', 'alignment-review-en.md'), `${generatedNotice}# Active alignment review\n`);
  await writeFile(join(root, 'delivery', 'alignment-review.md'), `${generatedNotice}# 活动对齐审阅\n`);

  assert.equal((await generateIndexesFromRoot({ map, lifecycleRoot: root })).ok, true);

  await unlink(join(root, 'delivery', 'alignment-review.md'));
  assert.equal((await generateIndexesFromRoot({ map, lifecycleRoot: root })).ok, false);
  await writeFile(join(root, 'delivery', 'alignment-review.md'), `${generatedNotice}# 活动对齐审阅\n`);

  await writeFile(join(root, 'delivery', 'notes.md'), '# This must not be silently ignored\n');
  assert.equal((await generateIndexesFromRoot({ map, lifecycleRoot: root })).ok, false);
});

test('rejects a legacy delivery artifact occupying the generated alignment projection locators', async (context) => {
  const root = await mkdtemp(join(tmpdir(), 'project-lifecycle-index-alignment-collision-'));
  context.after(() => rm(root, { recursive: true, force: true }));
  await mkdir(join(root, 'knowledge'), { recursive: true });
  await mkdir(join(root, 'delivery'), { recursive: true });
  const capabilitySource = (frontmatter) => `---\nid: ${frontmatter.id}\nknowledge_state: current\npaired_asset: ${frontmatter.paired_asset}\nlast_verified_baseline: ${frontmatter.last_verified_baseline}\nimplementation_refs:\n  - repo:src/alpha\nverification_refs:\n  - repo:test/alpha\n---\n`;
  for (const entry of capabilityPair) await writeFile(join(root, entry.locator), capabilitySource(entry.frontmatter));
  const collision = `---
schema_version: 1
artifact_id: alignment-review
artifact_kind: architecture
primary_route: PRD_DELIVERY
project_id_at_creation: sample-project
current_project_id: sample-project
domain_ids: [alpha-workspace]
knowledge_baseline: baseline-2
relationships: { feedback_ids: [], prd_ids: [], legacy_artifact_refs: [] }
retention_tier: active
reclassified_from_refs: []
obligations: []
---
`;
  await writeFile(join(root, 'delivery', 'alignment-review-en.md'), collision);
  await writeFile(join(root, 'delivery', 'alignment-review.md'), collision);

  const result = await generateIndexesFromRoot({ map, lifecycleRoot: root });

  assert.equal(result.ok, false);
});

test('does not exclude nested delivery overlays that share projection basenames', async (context) => {
  const root = await mkdtemp(join(tmpdir(), 'project-lifecycle-index-alignment-overlay-'));
  context.after(() => rm(root, { recursive: true, force: true }));
  await mkdir(join(root, 'knowledge'), { recursive: true });
  const capabilitySource = (frontmatter) => `---\nid: ${frontmatter.id}\nknowledge_state: current\npaired_asset: ${frontmatter.paired_asset}\nlast_verified_baseline: ${frontmatter.last_verified_baseline}\nimplementation_refs:\n  - repo:src/alpha\nverification_refs:\n  - repo:test/alpha\n---\n`;
  for (const entry of capabilityPair) await writeFile(join(root, entry.locator), capabilitySource(entry.frontmatter));
  const deliverySource = `---
schema_version: 1
artifact_id: prd-alignment-overlay
artifact_kind: prd
primary_route: PRD_DELIVERY
project_id_at_creation: sample-project
current_project_id: sample-project
domain_ids: [alpha-workspace]
knowledge_baseline: baseline-2
relationships: { feedback_ids: [], prd_ids: [], legacy_artifact_refs: [] }
retention_tier: active
reclassified_from_refs: []
obligations: []
---
`;
  const result = await generateIndexesFromRoot({
    map,
    lifecycleRoot: root,
    overlays: {
      'delivery/archive/alignment-review-en.md': deliverySource,
      'delivery/archive/alignment-review.md': deliverySource,
    },
  });
  assert.equal(result.ok, true, JSON.stringify(result));
  assert.match(result.value.en, /prd-alignment-overlay/u);
});

test('collects and renders only the active repository shard from disk', async (context) => {
  const repositoryId = 'backend';
  const crossMap = structuredClone(map);
  crossMap.repositories = [{
    id: repositoryId,
    purpose: { en: 'Owns backend knowledge.', 'zh-CN': '负责后端知识。' },
    portable_locator: 'github:example/backend',
    integration_ref: 'refs/heads/main',
    domain_ids: ['alpha-workspace'],
    knowledge_asset_locators: ['knowledge/alpha-workspace-en.md', 'knowledge/alpha-workspace.md'],
    accepted_revision: 'revision:backend',
  }];
  crossMap.domains[0].paired_assets.repository_id = repositoryId;
  const root = await mkdtemp(join(tmpdir(), 'project-lifecycle-index-shard-'));
  context.after(() => rm(root, { recursive: true, force: true }));
  await mkdir(join(root, 'knowledge'), { recursive: true });
  for (const entry of capabilityPair) {
    await writeFile(join(root, entry.locator), `---\nid: ${entry.frontmatter.id}\nknowledge_state: current\npaired_asset: ${entry.frontmatter.paired_asset}\nlast_verified_baseline: ${entry.frontmatter.last_verified_baseline}\nimplementation_refs:\n  - repo:src/alpha\nverification_refs:\n  - repo:test/alpha\n---\n`);
  }

  const result = await generateIndexesFromRoot({
    map: crossMap,
    lifecycleRoot: root,
    repository_id: repositoryId,
  });

  assert.equal(result.ok, true, JSON.stringify(result));
  assert.equal(result.value.files.every(({ repository_id: id }) => id === repositoryId), true);
  assert.equal(result.value.files.some(({ locator }) => locator === 'knowledge/INDEX-en.md'), true);
  const governance = generateIndexes({ map: crossMap, repository_id: null });
  assert.equal(governance.ok, true, JSON.stringify(governance));
  const governanceKnowledge = governance.value.files.find(({ locator }) => locator === 'knowledge/INDEX-en.md').content;
  assert.match(governanceKnowledge, /github:example\/backend\/docs\/project-lifecycle\/knowledge\/alpha-workspace-en\.md/);
  assert.match(governanceKnowledge, /knowledge: `remote`/);
});

test('ships paired index templates as exact output of the inert validated map', async () => {
  const templateMap = JSON.parse(await readFile(
    new URL('../../skills/maintain-project-knowledge/assets/project-map.json', import.meta.url),
    'utf8',
  ));
  const generated = generateIndexes({ map: templateMap });
  assert.equal(generated.ok, true);
  assert.equal(generated.value.en, await readFile(
    new URL('../../skills/maintain-project-knowledge/assets/INDEX-en.md', import.meta.url),
    'utf8',
  ));
  assert.equal(generated.value['zh-CN'], await readFile(
    new URL('../../skills/maintain-project-knowledge/assets/INDEX.md', import.meta.url),
    'utf8',
  ));
  const knowledgeEn = generated.value.files.find(({ locator }) => locator === 'knowledge/INDEX-en.md');
  const knowledgeZh = generated.value.files.find(({ locator }) => locator === 'knowledge/INDEX.md');
  assert.equal(knowledgeEn.content, await readFile(
    new URL('../../skills/maintain-project-knowledge/assets/knowledge-INDEX-en.md', import.meta.url),
    'utf8',
  ));
  assert.equal(knowledgeZh.content, await readFile(
    new URL('../../skills/maintain-project-knowledge/assets/knowledge-INDEX.md', import.meta.url),
    'utf8',
  ));
});
